dfnTrans: /Users/nataliia/Desktop/dfnGen-docs/Docs_PT/ParticleTracking_source/FuncDef.h File Reference
FuncDef.h File Reference
Data Structures
struct material
struct vertex
struct element
struct contam
Macros
#define pi 3.14159265359
Functions
void ReadInit ()
void ReadDataFiles ()
void AdjacentCells (int ln, int i, int j, int k)
void Convertto2d ()
void Convertto3d ()
void DarcyVelocity ()
struct matr MatrixProducts (double normxarea[][2], int number)
struct lb DefineBoundaryAngle (int i, unsigned int edge_1, unsigned int edge_2, int f1, int coorf)
void VelocityInteriorNode (double normxarea[][2], int i, int number, unsigned int indj[max_neighb], int vi)
void VelocityExteriorNode (double normxarea[][2], int i, int number, unsigned int indj[max_neighb], struct lb lbound, int vi)
void CheckNewCell ()
void ParticleTrack ()
struct intcoef CalculateWeights (int nn1, int nn2, int nn3)
void SearchNeighborCells (int nn1, int nn2, int nn3)
int InsideCell (unsigned int numc)
void NeighborCells (int k)
void PredictorStep ()
void CorrectorStep ()
void DefineTimeStep ()
int CheckDistance ()
void AcrossIntersection (int prevcell, int int1, int int2, int mixing_rule)
void ChangeFracture (int cell_win)
struct posit3d CalculatePosition3D ()
int InitCell ()
int InitPos ()
void Moving2Center (int nnp, int cellnumber)
int Moving2NextCell (int stuck, int k)
void BoundaryCells ()
int InitParticles_np (int k_current, int firstn, int lastn, int parts_fracture, int first_ind, int last_ind)
int InitParticles_eq (int k_current, int firstn, int lastn, double parts_dist, int first_ind, int last_ind)
int CornerVelocity (int i, int m1, int m2, int m3, int s1, int s2, int s3)
void ReadBoundaryNodes ()
FILE * OpenFile (char filen[120], char fileopt[2])
void ReadFEHMfile (int nedges)
void ReadPFLOTRANfile (int nedges)
void WritingInit ()
void Velocity3D ()
double CalculateCurrentDT ()
int Yindex (int nodenum, int np)
int Xindex (int nodenum, int np)
int CompleteMixingRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk)
int StreamlineRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk, int neighborcellind[4], int neighborfracind[4], int prevfrac, int prevcell)
void OutputVelocities ()
int XindexC (int nodenum, int ii)
int YindexC (int nodenum, int ii)
double DefineAngle (double u1, double u2, double v1, double v2)
void HalfPolygonVelocity (int i, int k, int fractn, int indc, unsigned int fractj[max_neighb])
struct posit3d CalculateVelocity3D ()
void BoundaryLine (int n1, int n2, int n3)
void CheckGrid ()
int BVelocityDirection (int b1, int b2)
double InOutFlowCell (int indcell, int int1, double nposx, double nposy)
void Moving2NextCellBound (int prevcell)
struct inpfile Control_File (char fileobject[], int ctr)
struct inpfile Control_Data (char fileobject[], int ctr)
void ParticleOutput (int currentt, int frac_p)
struct inpfile Control_Param (char fileobject[], int ctr)
void FlowInWeight (int numbpart)
int InitParticles_ones (int k_current, double inter_p[][4], int fracture, int parts_fracture, int ii, double thirdcoor, int zonenumb_in, int first_ind, int last_ind)
void Coordinations2D ()
void ReadAperture ()
void InitInMatrix ()
double TimeFromMatrix (double pdist)
void FinalPosition ()
struct lagrangian CalculateLagrangian (double xcurrent, double ycurrent, double zcurrent, double xprev, double yprev, double zprev)
void OutputMarPlumDisp (int currentnum, char path[125])
int String_Compare (char string1[], char string2[])
struct inpfile Control_File_Optional (char fileobject[], int ctr)
double TimeDomainRW (double time_advect)
int InitParticles_flux (int k_current, int firstn, int lastn, double weight_p)
Variables
char maindir [125]
double porosity
double density
unsigned long int timesteps
double thickness
double saturation
double timeunit
char controlfile [120]
double totalFluxIn
unsigned int pflotran
unsigned int fehm
unsigned int nnodes
unsigned int ncells
unsigned int nfract
unsigned int max_neighb
unsigned int npart
unsigned int np
unsigned int nzone_in
unsigned int * nodezonein
unsigned int * nodezoneout
unsigned int flag_w
struct material * fracture
struct vertex * node
struct contam * particle
struct element * cell
Macro Definition Documentation
pi
#define pi 3.14159265359
Definition at line 2 of file FuncDef.h.
Function Documentation
AcrossIntersection()
void AcrossIntersection (int prevcell, int int1, int int2, int mixing_rule)
Particle is moving through intersection line
Definition at line 2013 of file TrackingPart.c.
References CalculateWeights(), cell, vertex::cells, ChangeFracture(), CompleteMixingRandomSampling(), vertex::coord_xy, vertex::fracture, element::fracture, contam::intcell, mixing_rule, node, element::node_ind, np, particle, contam::position, contam::prev_pos, StreamlineRandomSampling(), element::veloc_ind, vertex::velocity, intcoef::weights, XindexC(), and YindexC().
AdjacentCells()
void AdjacentCells (int ln, int in, int jn, int kn)
The function defines adjacent triangular cells for each node
Definition at line 540 of file ReadGridInit.c.
References cell, vertex::cells, vertex::fracts, vertex::fracture, element::fracture, fracture, node, and vertex::numneighb.
Referenced by ReadDataFiles().
BoundaryCells()
void BoundaryCells ()
The function checks velocities at boundary nodes and fixes pathological cases.
In the rare event, when two velocity vectors are directed towards each other along the same cell edge, a particle will be stuck there. To avoid this situation, one of velocities is redirected along the edge with node associated with lower pressure value.
Definition at line 531 of file VelocityReconstruction.c.
References cell, vertex::cells, vertex::coord_xy, CornerVelocity(), DefineAngle(), fracture, vertex::indnodes, ncells, node, element::node_ind, vertex::numneighb, pi, vertex::pressure, element::veloc_ind, vertex::velocity, XindexC(), and YindexC().
Referenced by DarcyVelocity().
BoundaryLine()
void BoundaryLine (int n1, int n2, int n3)
BVelocityDirection()
int BVelocityDirection (int b1, int b2)
CalculateCurrentDT()
double CalculateCurrentDT ()
Functions returns particle instanteneous time step
Definition at line 2527 of file TrackingPart.c.
References contam::cell, cell, node, element::node_ind, np, particle, vertex::timestep, element::veloc_ind, and contam::weight.
Referenced by CheckDistance(), CheckNewCell(), CorrectorStep(), and PredictorStep().
CalculateLagrangian()
struct lagrangian CalculateLagrangian (double xcurrent, double ycurrent, double zcurrent, double xprev, double yprev, double zprev)
Function calculates Lagrangian variables: tau and beta.
Definition at line 3140 of file TrackingPart.c.
References vertex::aperture, lagrangian::betta, CalculateVelocity3D(), contam::cell, cell, posit3d::cord3, lagrangian::initx, lagrangian::inity, lagrangian::initz, lagvariable, node, element::node_ind, np, particle, and lagrangian::tau.
CalculatePosition3D()
struct posit3d CalculatePosition3D ()
Function calculates 3D coordinates of current particle's position at 2D fracture plane
Definition at line 213 of file RotateFracture.c.
References vertex::coord, vertex::coord_xy, posit3d::cord3, material::firstnode, contam::fracture, fracture, node, np, particle, contam::position, and material::rot3mat.
Referenced by ChangeFracture().
CalculateVelocity3D()
struct posit3d CalculateVelocity3D ()
The function converts particle's 2D velocity vector to 3D velocity vector
Definition at line 335 of file RotateFracture.c.
References posit3d::cord3, contam::fracture, fracture, np, particle, material::rot3mat, and contam::velocity.
Referenced by CalculateLagrangian().
CalculateWeights()
struct intcoef CalculateWeights (int nn1, int nn2, int nn3)
Function calculates interpolation weights for velocity instanteneous particles velocity and time step.
Definition at line 1416 of file TrackingPart.c.
References vertex::coord_xy, node, np, particle, intcoef::weights, Xindex(), and Yindex().
Referenced by AcrossIntersection(), CheckNewCell(), InOutFlowCell(), and InsideCell().
ChangeFracture()
void ChangeFracture (int cell_win)
This function recalculates particles coordinations at intersection lines. Particles XY coordinations at one fracture are recalculated to 3D positions and then new XY coordinations of an intersecting fracture are defined.
Definition at line 183 of file RotateFracture.c.
References CalculatePosition3D(), contam::cell, cell, element::fracture, contam::fracture, fracture, np, particle, contam::position, and material::rot2mat.
Referenced by AcrossIntersection(), and InOutFlowCell().
CheckDistance()
int CheckDistance ()
Function checks the distance from particle to intersection line when particles is located at the intersection triangular cell
Definition at line 1655 of file TrackingPart.c.
References CalculateCurrentDT(), contam::cell, cell, CheckNewCell(), vertex::coord_xy, vertex::fracture, fracture, vertex::indnodes, no_out, node, element::node_ind, np, vertex::numneighb, particle, ParticleOutput(), contam::position, PredictorStep(), contam::prev_pos, t, t_adv, t_adv0, contam::t_adv_diff, contam::t_diff, tdrw, tdrw_o, contam::time, timediff, TimeDomainRW(), Xindex(), and Yindex().
CheckGrid()
void CheckGrid ()
The function checks the grid: looking for nodes that are defined as internal or external, but belong to two fractures and should be defined as interface nodes
Definition at line 1055 of file ReadGridInit.c.
References fracture, nnodes, node, and vertex::numneighb.
Referenced by main().
CheckNewCell()
void CheckNewCell ()
Function performs a check, did particle move to a new triangular cell during last time step or stayed at the same cell
Definition at line 1273 of file TrackingPart.c.
References CalculateCurrentDT(), CalculateWeights(), contam::cell, cell, FLAG_OUT, contam::fracture, node, element::node_ind, np, vertex::numneighb, particle, contam::position, contam::prev_pos, SearchNeighborCells(), contam::velocity, contam::weight, and intcoef::weights.
Referenced by CheckDistance().
CompleteMixingRandomSampling()
int CompleteMixingRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk)
Particle motion at a fracture intersection is determined by the streamline routing rule Arg 1: Cross product to define outgoing and incoming cells. Vector contains value for each cell at the intersection Arg 2: Vector of the speed squared for each cell at the intersection Arg 3: index of current cell in int1 node list Arg 4: int1 is the index of the node of the incoming cell that lies on the intersection Arg 5: indk gives the position in the list of the 4 intersection cells that is previous cell Return: The Exit cell at the intersection
Definition at line 2344 of file TrackingPart.c.
References vertex::cells, and node.
Referenced by AcrossIntersection().
Control_Data()
struct inpfile Control_Data (char fileobject[], int ctr)
The function reads control file with input parameters to dfnTrans; returns input parameter value. If the parameter is not defined in the control file, the program is terminated.
Definition at line 1201 of file ReadGridInit.c.
References controlfile, inpfile::flag, OpenFile(), inpfile::param, and String_Compare().
Referenced by InitPos(), main(), and ReadBoundaryNodes().
Control_File()
struct inpfile Control_File (char fileobject[], int ctr)
The function reads control file with input parameters to dfnTrans; returns the file name and/or input parameter value. If the parameter is not defined in the control file, the program is terminated.
Definition at line 1090 of file ReadGridInit.c.
References controlfile, inpfile::filename, inpfile::flag, OpenFile(), inpfile::param, and String_Compare().
Referenced by InitInMatrix(), InitPos(), main(), OutputMarPlumDisp(), ParticleTrack(), ReadAperture(), ReadBoundaryNodes(), ReadDataFiles(), ReadFEHMfile(), ReadInit(), and ReadPFLOTRANfile().
Control_File_Optional()
struct inpfile Control_File_Optional (char fileobject[], int ctr)
The function reads control file with input parameters to dfnTrans; returns the file name and/or input parameter value. This function is called for the optional parameters only. If the parameter is not defined in the control file, the default value is used.
Definition at line 1135 of file ReadGridInit.c.
References controlfile, inpfile::filename, inpfile::flag, OpenFile(), inpfile::param, and String_Compare().
Referenced by InitPos(), ParticleTrack(), and ReadInit().
Control_Param()
struct inpfile Control_Param (char fileobject[], int ctr)
The function reads control file with input parameters to dfnTrans; returns input parameter value. If the parameter is not defined in the control file, the program is terminated.
Definition at line 1245 of file ReadGridInit.c.
References controlfile, inpfile::flag, OpenFile(), inpfile::param, and String_Compare().
Referenced by InitPos(), main(), ParticleTrack(), and TimeFromMatrix().
Convertto2d()
void Convertto2d ()
The function uses rotation matrix and fracture's normal vector to rotate fracture from its position in 3D to XY plane
if node belongs to intersection, belongs to two fractures
Definition at line 17 of file RotateFracture.c.
References vertex::coord, vertex::coord_xy, vertex::fracture, fracture, nfract, nnodes, node, material::nvect_xy, pi, material::rot2mat, material::rot3mat, and material::theta.
Referenced by main().
Convertto3d()
void Convertto3d ()
The function uses rotation matrix to rotate fracture from its position in XY plane to 3D domain
Definition at line 130 of file RotateFracture.c.
References fracture, nfract, material::nvect_z, pi, material::rot3mat, and material::theta.
Referenced by main().
Coordinations2D()
void Coordinations2D ()
The function outputs 2D coordinations of nodes: every fracture into separate file. Those files are used as input to gstat for length correlation of aperture.
Definition at line 360 of file RotateFracture.c.
References vertex::coord_xy, fracture, nfract, nnodes, node, and OpenFile().
CornerVelocity()
int CornerVelocity (int i, int m1, int m2, int m3, int s1, int s2, int s3)
The Function identifies pathologycal cases at corner of fracture boundary. The angle between velocity on corner node and velocities/edges on surrounding boundary nodes are calculated. Then, if velocity is pointing outside of fracture, turns the velocity direction along the fracture edge.
Definition at line 771 of file VelocityReconstruction.c.
References vertex::coord_xy, DefineAngle(), node, pi, vertex::velocity, XindexC(), and YindexC().
Referenced by BoundaryCells().
CorrectorStep()
void CorrectorStep ()
Corrector step in Predictor-Corrector technique. Function calculates new particle position using calculated velocity in Predictor step.
Definition at line 1576 of file TrackingPart.c.
References CalculateCurrentDT(), contam::cell, cell, element::node_ind, np, particle, contam::position, contam::prev_pos, element::veloc_ind, and contam::velocity.
DarcyVelocity()
void DarcyVelocity ()
Function performs Darcy's velocity reconstruction (main function of Darcy velocities reconstruction procedure) using linear least square algorithm. Flow solver provides flow fluxes on each edge of control volume cells. Velocity on each control volume cell center (each node) is reconstructed using flow fluxes.
Velocity of interior and interior-interface nodes is reconstructed according to Eq.5 (Painter,2011); exterior node' velocity according to Eq.7 (Painter, 2011)
Function makes a loop over all nodes and calls functions for velocity reconstruction depending of type of the node (external, internal, internal-interface, external interface)
Definition at line 29 of file VelocityReconstruction.c.
References BoundaryCells(), vertex::coord_xy, DefineBoundaryAngle(), fehm, vertex::fracture, fracture, HalfPolygonVelocity(), vertex::indnodes, max_neighb, nnodes, node, vertex::numneighb, pflotran, vertex::velocity, VelocityExteriorNode(), and VelocityInteriorNode().
Referenced by main().
DefineAngle()
double DefineAngle (double u1, double u2, double v1, double v2)
Function defines an angle between two edges of voronoy cell
Definition at line 415 of file VelocityReconstruction.c.
References lb::angle.
Referenced by BoundaryCells(), CornerVelocity(), and DefineBoundaryAngle().
DefineBoundaryAngle()
struct lb DefineBoundaryAngle (int i, unsigned int edge_1, unsigned int edge_2, int f1, int coorf)
The function defines angle between two edges of a boundary cell and return the result. The angle is used in flow velocity reconstruction on fracture edge.
Definition at line 367 of file VelocityReconstruction.c.
References lb::angle, vertex::coord_xy, DefineAngle(), fracture, vertex::indnodes, lb::length_b, node, and lb::norm.
Referenced by DarcyVelocity(), and HalfPolygonVelocity().
DefineTimeStep()
void DefineTimeStep ()
Function performs a loop through all the nodes in the mesh and defines a time step at each node. The time step of particles will be interpolated from time steps defined at each node.
Definition at line 1622 of file TrackingPart.c.
References nnodes, node, vertex::timestep, and vertex::velocity.
Referenced by main().
FinalPosition()
void FinalPosition ()
Function calculates particles final position at out-flow boundary
Definition at line 2996 of file TrackingPart.c.
References contam::cell, cell, vertex::cells, vertex::coord_xy, vertex::indnodes, node, element::node_ind, np, vertex::numneighb, particle, contam::position, contam::prev_pos, contam::time, Xindex(), and Yindex().
FlowInWeight()
void FlowInWeight (int numberpart)
Function calculates particle's in-flow flux weight. Used in option #1, #2, #3.
Definition at line 861 of file InitialPartPositions.c.
References contam::cell, cell, contam::fl_weight, InitCell(), node, element::node_ind, np, vertex::numneighb, particle, and contam::weight.
Referenced by ParticleTrack().
HalfPolygonVelocity()
void HalfPolygonVelocity (int i, int k, int fractn, int indc, unsigned int fractj[max_neighb])
Velocity reconstruction on an intersection node. In this case, the control volume cell is devided onto two polygons by intersection line. The velocity reconstruction is performed on each part of control volume cell at intersection.
Definition at line 944 of file VelocityReconstruction.c.
References vertex::area, cell, vertex::cells, vertex::coord_xy, DefineBoundaryAngle(), fehm, fracture, vertex::indnodes, max_neighb, node, pflotran, vertex::type, vertex::typeN, element::veloc_ind, VelocityExteriorNode(), and VelocityInteriorNode().
Referenced by DarcyVelocity().
InitCell()
int InitCell ()
Function performs a search to find cell Id where the particle was initially placed.
Definition at line 621 of file InitialPartPositions.c.
References vertex::cells, InsideCell(), node, nodezonein, vertex::numneighb, and nzone_in.
Referenced by FlowInWeight().
InitInMatrix()
void InitInMatrix ()
Function performs data reading from files for Option #5, init_matrix. In this option particles are placed at random positions in matrix, the time to move from initial position to nearest fracture is calculated in function TimeFromMatrix.
Input files ParticleInitCoordR.dat and ClosestNodeR.inp provide particles initial positions at matrix and te closes node ID at DFN mesh, respectively.
Definition at line 968 of file InitialPartPositions.c.
References contam::cell, Control_File(), vertex::coord, vertex::coord_xy, contam::fl_weight, vertex::fracture, contam::fracture, contam::intcell, node, npart, OpenFile(), particle, contam::position, contam::prev_pos, contam::time, TimeFromMatrix(), contam::velocity, and contam::weight.
Referenced by InitPos().
InitParticles_eq()
int InitParticles_eq (int k_current, int firstn, int lastn, double parts_dist, int first_ind, int last_ind)
Function defines particles initial positions at a single fracture edge, using calculated before distance between particles. Option #2, init_eqd.
Definition at line 711 of file InitialPartPositions.c.
References vertex::coord_xy, contam::fl_weight, vertex::fracture, contam::fracture, fracture, contam::intcell, node, npart, particle, contam::position, contam::time, and contam::velocity.
Referenced by InitPos().
InitParticles_flux()
int InitParticles_flux (int k_current, int first_ind, int last_ind, double weight_p)
Function defines particle's initial positions at single fracture edge in Option #6. Particles are placed according to input flux weights. In this case, all the particles have the same flux weight, but number of particles per fracture edge depends on in-flow flux of this fracture.
Definition at line 1095 of file InitialPartPositions.c.
References contam::cell, vertex::coord_xy, density, contam::fl_weight, vertex::fracture, contam::fracture, contam::intcell, node, nodezonein, np, npart, vertex::numneighb, particle, contam::position, contam::time, and contam::velocity.
Referenced by InitPos().
InitParticles_np()
int InitParticles_np (int k_current, int firstnd, int lastnd, int parts_fracture, int first_ind, int last_ind)
Function defines particle's initial positions on a single fracture edge. Option #1, init_nf
Definition at line 660 of file InitialPartPositions.c.
References vertex::coord_xy, contam::fl_weight, vertex::fracture, contam::fracture, contam::intcell, node, npart, particle, contam::position, contam::time, and contam::velocity.
Referenced by InitPos().
InitParticles_ones()
int InitParticles_ones (int k_current, double inter_p[][4], int fracture_n, int parts_fracture, int ii, double thirdcoor, int zonenumb_in, int first_ind, int last_ind)
Function defines particles initial positions in option #3, where user defines region at in-flow boundary face for particles.
Definition at line 764 of file InitialPartPositions.c.
References contam::fl_weight, contam::fracture, fracture, contam::intcell, npart, particle, contam::position, material::rot2mat, contam::time, and contam::velocity.
Referenced by InitPos().
InitPos()
int InitPos ()
Function defines the required option of particles initial positions defined at input control file; calculates number of particles, allocates memory.
First option init_nf: equal number of particles on every boundary edge regardless of edge length
Second option init_eqd: calculate total length of boundary edges; define the distance between particles and place particles equidistant from each other on all edges
Third option init_oneregion: user specifies a region and all particles start from the fracture edges that located inside the region
Fourth option init_random: particles will be set randomly over all fractures surfaces; in this case the particles are weighted acoording to the aperture
5th option init_matrix: particles are set randomly in rock matrix, their time from initial positions is calculated, then particles move through fractures to out-flow boundary. This option requires preprocessing; the script RandomPositGener.py will provide necessary input files
Sixth option init_flux: place particles according to input fluxes. Each particle has the same flux weight. The number of particles are placed propportionally to inflow flux on each cell and fracture edge.
Definition at line 21 of file InitialPartPositions.c.
References vertex::aperture, contam::cell, cell, Control_Data(), Control_File(), Control_File_Optional(), Control_Param(), vertex::coord, inpfile::filename, contam::fl_weight, inpfile::flag, flag_w, vertex::fracture, element::fracture, contam::fracture, fracture, InitInMatrix(), InitParticles_eq(), InitParticles_flux(), InitParticles_np(), InitParticles_ones(), InsideCell(), Moving2Center(), ncells, node, element::node_ind, nodezonein, npart, nzone_in, inpfile::param, particle, contam::time, totalFluxIn, and contam::velocity.
Referenced by ParticleTrack().
InOutFlowCell()
double InOutFlowCell (int indcell, int int1, double nposx, double nposy)
Function defines if velocities on cell vertices pointing in or out of intersection line
Definition at line 1949 of file TrackingPart.c.
References CalculateWeights(), contam::cell, cell, ChangeFracture(), vertex::coord_xy, contam::fracture, node, element::node_ind, np, particle, contam::position, element::veloc_ind, vertex::velocity, intcoef::weights, XindexC(), and YindexC().
InsideCell()
int InsideCell (unsigned int numc)
Function checks if particle is in the cell (numc is cell ID)
Definition at line 1487 of file TrackingPart.c.
References CalculateWeights(), contam::cell, cell, contam::intcell, node, element::node_ind, np, particle, contam::weight, and intcoef::weights.
Referenced by InitCell(), InitPos(), Moving2Center(), and NeighborCells().
MatrixProducts()
struct matr MatrixProducts (double normxarea[][2], int number)
Function performs matrix dot product (GTG)-1 and returns the result.
Definition at line 318 of file VelocityReconstruction.c.
References matr::matinv, and matr::matrinvG.
Referenced by VelocityExteriorNode(), and VelocityInteriorNode().
Moving2Center()
void Moving2Center (int nnp, int cellnumber)
Function moves particle to the center of the same cell
Definition at line 2440 of file TrackingPart.c.
References cell, vertex::coord_xy, InsideCell(), node, element::node_ind, particle, contam::position, Xindex(), and Yindex().
Referenced by InitPos(), Moving2NextCell(), and Moving2NextCellBound().
Moving2NextCell()
int Moving2NextCell (int stuck, int k)
Functions performs the movement of particle from one cell to the center of neighbouring cell.
Definition at line 2471 of file TrackingPart.c.
References contam::cell, cell, vertex::cells, fracture, Moving2Center(), node, np, and particle.
Moving2NextCellBound()
void Moving2NextCellBound (int prevcell)
In the pathological rare case, when particle is out of fracture, the function is called and it's moving particle to internal cell
Definition at line 2572 of file TrackingPart.c.
References contam::cell, cell, vertex::cells, fracture, Moving2Center(), node, element::node_ind, np, and particle.
NeighborCells()
void NeighborCells (int k)
Function checks neighboring cells to find a particle
Definition at line 1600 of file TrackingPart.c.
References vertex::cells, fracture, InsideCell(), node, np, and particle.
Referenced by SearchNeighborCells().
OpenFile()
FILE* OpenFile (char filen[120], char fileopt[2])
The function opens file for reading or writing. If error - the program is terminated.
Definition at line 728 of file ReadGridInit.c.
Referenced by Control_Data(), Control_File(), Control_File_Optional(), Control_Param(), Coordinations2D(), InitInMatrix(), OutputMarPlumDisp(), ParticleTrack(), ReadAperture(), ReadBoundaryNodes(), ReadDataFiles(), ReadFEHMfile(), ReadInit(), ReadPFLOTRANfile(), Velocity3D(), and WritingInit().
OutputMarPlumDisp()
void OutputMarPlumDisp (int currentnum, char path[125])
This function is used when particles trajectories should be output in format that MARFA and/or PLUMECALC codes will be able to read and process.
Definition at line 19 of file output.c.
References cell, Control_File(), inpfile::filename, maindir, marfa, OpenFile(), plumec, timeunit, and traj_o.
OutputVelocities()
void OutputVelocities ()
This function is called to output velocities on nodes in the order of fractture IDs. The output can be used to visualise flow field of 2D reconstructed Darcy velocities in 3D simulation domain
Definition at line 253 of file VelocityReconstruction.c.
References fracture, maindir, nfract, nnodes, node, and vertex::velocity.
ParticleOutput()
void ParticleOutput (int currentt, int fract_p)
The function of particles trajectories outputs. Function is called at every intersection and outputs to file at each segment of particles trajectory: from intersection to intersection. The curvature of the trajectory is defined and dictate number of time steps for outputs (unless user requested every time step output).
Definition at line 2669 of file TrackingPart.c.
References tfile.
Referenced by CheckDistance().
ParticleTrack()
void ParticleTrack ()
The main driving function of particles tracking procedure.
The all necessary options for particle tracking and for the outputs are read from input control file.
The subroutine for particle initial positions is called.
External loop on paticles is organised. One particle at a time.
Internal loop on time steps, where particles are mobing through fracture network. 4.1 Predictor -corrector technique is used for particles to move through fractures. 4.2 Complete mixing or streamline routing rule (defined by user) are used on intersections. 4.3 Particles data outputs.
Definition at line 66 of file TrackingPart.c.
References all_out, avs_o, Control_File(), Control_File_Optional(), Control_Param(), vertex::coord, curv_o, disp_o, inpfile::filename, inpfile::flag, flag_w, FlowInWeight(), frac_o, vertex::fracture, InitPos(), maindir, marfa, mixing_rule, no_out, node, nodezonein, nodezoneout, np, OpenFile(), inpfile::param, plumec, String_Compare(), t, tdrw, tdrw_diffcoeff, tdrw_o, tdrw_porosity, tfile, timesteps, timeunit, and traj_o.
Referenced by main().
PredictorStep()
void PredictorStep ()
Predictor step in Predictor-Corrector technique. Function calculates new velocities and new particle position.
Definition at line 1541 of file TrackingPart.c.
References CalculateCurrentDT(), contam::cell, cell, node, element::node_ind, np, particle, contam::position, vertex::pressure, contam::pressure, contam::prev_pos, element::veloc_ind, vertex::velocity, contam::velocity, and contam::weight.
Referenced by CheckDistance().
ReadAperture()
void ReadAperture ()
The function reads apertures of fractures in DFN. Aperture can be defined for each fracture or for every node/cell, representing internal heterogeneity.
Definition at line 1289 of file ReadGridInit.c.
References vertex::aperture, Control_File(), inpfile::filename, vertex::fracture, fracture, nfract, nnodes, node, and OpenFile().
Referenced by ReadDataFiles().
ReadBoundaryNodes()
void ReadBoundaryNodes ()
The functions reads node's IDs assigned to in-flow and out-flow boundaries. the total input flow flux is calculated.
Definition at line 581 of file ReadGridInit.c.
References Control_Data(), Control_File(), density, inpfile::filename, vertex::flux, maindir, node, nodezonein, nodezoneout, vertex::numneighb, nzone_in, OpenFile(), totalFluxIn, and vertex::typeN.
Referenced by main().
ReadDataFiles()
void ReadDataFiles ()
The function reads DFN mesh from inp and stor files
if no aperture file specified, the aperture of all fractures will be equal to thickness value
Definition at line 180 of file ReadGridInit.c.
References AdjacentCells(), vertex::aperture, vertex::area, cell, vertex::cells, Control_File(), fehm, inpfile::filename, material::firstcell, material::firstnode, vertex::flux, vertex::fracts, vertex::fracture, element::fracture, fracture, vertex::indnodes, material::lastnode, max_neighb, ncells, nfract, nnodes, node, material::numbcells, vertex::numneighb, OpenFile(), pflotran, ReadAperture(), ReadFEHMfile(), ReadPFLOTRANfile(), thickness, vertex::type, vertex::typeN, and element::veloc_ind.
Referenced by main().
ReadFEHMfile()
void ReadFEHMfile (int nedges)
The function opens and reads FEHM outputs; read in flow fluxes and cell volumes.
Definition at line 879 of file ReadGridInit.c.
References Control_File(), max_neighb, nnodes, node, OpenFile(), and vertex::pressure.
Referenced by ReadDataFiles().
ReadInit()
void ReadInit ()
The function reads total number of nodes, triangular cells, fractures in DFN mesh. The memory is allocated for data structures: NODE, CELL, FRACTURE
Definition at line 16 of file ReadGridInit.c.
References vertex::area, cell, vertex::cells, Control_File(), Control_File_Optional(), vertex::flux, vertex::fracts, fracture, vertex::indnodes, max_neighb, ncells, nfract, nnodes, node, material::nvect_xy, material::nvect_z, OpenFile(), material::theta, and vertex::type.
Referenced by main().
ReadPFLOTRANfile()
void ReadPFLOTRANfile (int nedges)
The function opens and reads PFLOTRAN files, read in flow fluxes, areas, pressure.
Definition at line 742 of file ReadGridInit.c.
References vertex::area, Control_File(), density, inpfile::filename, inpfile::flag, vertex::flux, nnodes, node, vertex::numneighb, OpenFile(), and vertex::pressure.
Referenced by ReadDataFiles().
SearchNeighborCells()
void SearchNeighborCells (int nn1, int nn2, int nn3)
Function performs a search of neighbouring cells of current particles position.
Definition at line 1450 of file TrackingPart.c.
References cell, NeighborCells(), np, and particle.
Referenced by CheckNewCell().
StreamlineRandomSampling()
int StreamlineRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk, int neighborcellind[4], int neighborfracind[4], int prevfrac, int prevcell)
Particle motion at a fracture intersection is determined by the streamline routing rule Arg 1: Cross product to define outgoing and incoming cells. Vector contains value for each cell at the intersection Arg 2: Vector of the speed squared for each cell at the intersection Arg 3: index of current cell in int1 node list Arg 4: int1 is the index of the node of the incoming cell that lies on the intersection Arg 5: indk gives the position in the list of the 4 intersection cells that is previous cell Arg 6: Vector of the indicies for the 4 neighboring cells Arg 7: Vector of the fracture index for the 4 neighboring cells Arg 8: Fracture a particle is coming from Arg 9: Cell index a particle is coming from Return: The Exit cell at the intersection
Definition at line 2142 of file TrackingPart.c.
References cell, vertex::cells, fracture, and node.
Referenced by AcrossIntersection().
String_Compare()
int String_Compare (char string1[], char string2[])
The finction performs a string comparison, used in the control file reading.
Definition at line 1176 of file ReadGridInit.c.
Referenced by Control_Data(), Control_File(), Control_File_Optional(), Control_Param(), main(), and ParticleTrack().
TimeDomainRW()
double TimeDomainRW (double time_advect)
Time Domain Random Walk (TDRW) procedure. Returns a diffusion time of particle per racture. Called at each intersection.
Definition at line 3175 of file TrackingPart.c.
References vertex::aperture, contam::cell, cell, material::firstnode, contam::fracture, fracture, node, element::node_ind, np, particle, pi, tdrw_diffcoeff, tdrw_porosity, and timediff.
Referenced by CheckDistance().
TimeFromMatrix()
double TimeFromMatrix (double pdist)
Option #5. Estimation of travel time of particles moving from matrix to the closest fracture.
Definition at line 1062 of file InitialPartPositions.c.
References Control_Param(), inpfile::param, pi, and timeunit.
Referenced by InitInMatrix().
Velocity3D()
void Velocity3D ()
Recalculates 2D velocities at XY fracture plane to 3D velocties in the simulation domain. This procedure is not used for particle tracking, but can be used for velocity field visualization.
Definition at line 246 of file RotateFracture.c.
References posit3d::cord3, vertex::fracture, fracture, maindir, nnodes, node, OpenFile(), material::rot3mat, and vertex::velocity.
Referenced by main().
VelocityExteriorNode()
void VelocityExteriorNode (double norm_xarea[][2], int i, int number, unsigned int indj[max_neighb], struct lb lbound, int vi)
The function reconstructs Darcy velocity on exterior (boundary) node
Definition at line 465 of file VelocityReconstruction.c.
References density, vertex::flux, lb::length_b, matr::matinv, matr::matrinvG, MatrixProducts(), node, lb::norm, porosity, timeunit, and vertex::velocity.
Referenced by DarcyVelocity(), and HalfPolygonVelocity().
VelocityInteriorNode()
void VelocityInteriorNode (double normx_area[][2], int i, int number, unsigned int indj[max_neighb], int vi)
The function reconstructs Darcy velocity on interior cell center, at interior node
Definition at line 426 of file VelocityReconstruction.c.
References density, vertex::flux, matr::matinv, matr::matrinvG, MatrixProducts(), node, porosity, timeunit, and vertex::velocity.
Referenced by DarcyVelocity(), and HalfPolygonVelocity().
WritingInit()
void WritingInit ()
Functions write the data structure of nodes, cells and fractures into files in ASCII format with detail explanations. This output is optional and can be helpful in code debugging.
Definition at line 981 of file ReadGridInit.c.
References cell, inpfile::filename, fracture, maindir, nfract, nnodes, node, material::numbcells, vertex::numneighb, and OpenFile().
Referenced by main().
Xindex()
int Xindex (int nodenum, int nnp)
Functions returns the index of X coordination of intersection node
Definition at line 2550 of file TrackingPart.c.
References fracture, node, and particle.
Referenced by CalculateWeights(), CheckDistance(), FinalPosition(), and Moving2Center().
XindexC()
int XindexC (int nodenum, int ii)
Functions returns the index of X coordination of intersection node (cells)
Definition at line 922 of file VelocityReconstruction.c.
References cell, fracture, and node.
Referenced by AcrossIntersection(), BoundaryCells(), CornerVelocity(), and InOutFlowCell().
Yindex()
int Yindex (int nodenum, int nnp)
Functions returns the index of Y coordination of intersection node
Definition at line 2561 of file TrackingPart.c.
References fracture, node, and particle.
Referenced by CalculateWeights(), CheckDistance(), FinalPosition(), and Moving2Center().
YindexC()
int YindexC (int nodenum, int ii)
Functions returns the index of Y coordination of intersection node (cells)
Definition at line 933 of file VelocityReconstruction.c.
References cell, fracture, and node.
Referenced by AcrossIntersection(), BoundaryCells(), CornerVelocity(), and InOutFlowCell().
Variable Documentation
cell
struct element* cell
DYNAMIC ARRAY OF TRIANGULAR CELLS in DFN mesh
Definition at line 42 of file main.c.
Referenced by AcrossIntersection(), AdjacentCells(), BoundaryCells(), CalculateCurrentDT(), CalculateLagrangian(), ChangeFracture(), CheckDistance(), CheckNewCell(), CorrectorStep(), FinalPosition(), FlowInWeight(), HalfPolygonVelocity(), InitPos(), InOutFlowCell(), InsideCell(), main(), Moving2Center(), Moving2NextCell(), Moving2NextCellBound(), OutputMarPlumDisp(), PredictorStep(), ReadDataFiles(), ReadInit(), SearchNeighborCells(), StreamlineRandomSampling(), TimeDomainRW(), WritingInit(), XindexC(), and YindexC().
controlfile
char controlfile[120]
Name of Control file with all inut parameters to dfnTrans, given by user at the command line
Definition at line 44 of file main.c.
Referenced by Control_Data(), Control_File(), Control_File_Optional(), Control_Param(), and main().
density
double density
Flow density, defined by user
Definition at line 47 of file main.c.
Referenced by InitParticles_flux(), main(), ReadBoundaryNodes(), ReadPFLOTRANfile(), VelocityExteriorNode(), and VelocityInteriorNode().
fehm
unsigned int fehm
fehm=1 when FEHM flow solver is used
Definition at line 28 of file main.c.
Referenced by DarcyVelocity(), HalfPolygonVelocity(), and ReadDataFiles().
flag_w
unsigned int flag_w
Definition at line 38 of file main.c.
Referenced by InitPos(), and ParticleTrack().
fracture
struct material* fracture
DYNAMIC ARRAY OF FRACTURES
Definition at line 39 of file main.c.
Referenced by AdjacentCells(), BoundaryCells(), CalculatePosition3D(), CalculateVelocity3D(), ChangeFracture(), CheckDistance(), CheckGrid(), Convertto2d(), Convertto3d(), Coordinations2D(), DarcyVelocity(), DefineBoundaryAngle(), HalfPolygonVelocity(), InitParticles_eq(), InitParticles_ones(), InitPos(), main(), Moving2NextCell(), Moving2NextCellBound(), NeighborCells(), OutputVelocities(), ReadAperture(), ReadDataFiles(), ReadInit(), StreamlineRandomSampling(), TimeDomainRW(), Velocity3D(), WritingInit(), Xindex(), XindexC(), Yindex(), and YindexC().
maindir
char maindir[125]
The directory/path for particle tracking outputs, defined by user
Definition at line 43 of file main.c.
Referenced by main(), OutputMarPlumDisp(), OutputVelocities(), ParticleTrack(), ReadBoundaryNodes(), Velocity3D(), and WritingInit().
max_neighb
unsigned int max_neighb
maximum number of nodes neighbours/connections
Definition at line 32 of file main.c.
Referenced by DarcyVelocity(), HalfPolygonVelocity(), ReadDataFiles(), ReadFEHMfile(), and ReadInit().
ncells
unsigned int ncells
total number of triangular elements in the DFN mesh
Definition at line 30 of file main.c.
Referenced by BoundaryCells(), InitPos(), ReadDataFiles(), and ReadInit().
nfract
unsigned int nfract
total number of fractures in the DFN mesh
Definition at line 31 of file main.c.
Referenced by Convertto2d(), Convertto3d(), Coordinations2D(), OutputVelocities(), ReadAperture(), ReadDataFiles(), ReadInit(), and WritingInit().
nnodes
unsigned int nnodes
total number of nodes in the DFN mesh
Definition at line 29 of file main.c.
Referenced by CheckGrid(), Convertto2d(), Coordinations2D(), DarcyVelocity(), DefineTimeStep(), OutputVelocities(), ReadAperture(), ReadDataFiles(), ReadFEHMfile(), ReadInit(), ReadPFLOTRANfile(), Velocity3D(), and WritingInit().
node
struct vertex* node
DYNAMIC ARRAY OF NODES in DFN mesh
Definition at line 40 of file main.c.
Referenced by AcrossIntersection(), AdjacentCells(), BoundaryCells(), CalculateCurrentDT(), CalculateLagrangian(), CalculatePosition3D(), CalculateWeights(), CheckDistance(), CheckGrid(), CheckNewCell(), CompleteMixingRandomSampling(), Convertto2d(), Coordinations2D(), CornerVelocity(), DarcyVelocity(), DefineBoundaryAngle(), DefineTimeStep(), FinalPosition(), FlowInWeight(), HalfPolygonVelocity(), InitCell(), InitInMatrix(), InitParticles_eq(), InitParticles_flux(), InitParticles_np(), InitPos(), InOutFlowCell(), InsideCell(), main(), Moving2Center(), Moving2NextCell(), Moving2NextCellBound(), NeighborCells(), OutputVelocities(), ParticleTrack(), PredictorStep(), ReadAperture(), ReadBoundaryNodes(), ReadDataFiles(), ReadFEHMfile(), ReadInit(), ReadPFLOTRANfile(), StreamlineRandomSampling(), TimeDomainRW(), Velocity3D(), VelocityExteriorNode(), VelocityInteriorNode(), WritingInit(), Xindex(), XindexC(), Yindex(), and YindexC().
nodezonein
unsigned int* nodezonein
pointer to the dynamic array with a list of in-flow boundary nodes
Definition at line 36 of file main.c.
Referenced by InitCell(), InitParticles_flux(), InitPos(), main(), ParticleTrack(), and ReadBoundaryNodes().
nodezoneout
unsigned int* nodezoneout
pointer to the dynamic array with a list of out-flow boundary nodes
Definition at line 37 of file main.c.
Referenced by main(), ParticleTrack(), and ReadBoundaryNodes().
np
unsigned int np
index of current particle, idex in particle's loop
Definition at line 34 of file main.c.
Referenced by AcrossIntersection(), CalculateCurrentDT(), CalculateLagrangian(), CalculatePosition3D(), CalculateVelocity3D(), CalculateWeights(), ChangeFracture(), CheckDistance(), CheckNewCell(), CorrectorStep(), FinalPosition(), FlowInWeight(), InitParticles_flux(), InOutFlowCell(), InsideCell(), Moving2NextCell(), Moving2NextCellBound(), NeighborCells(), ParticleTrack(), PredictorStep(), SearchNeighborCells(), and TimeDomainRW().
npart
unsigned int npart
initial number of particles set up in the simulation
Definition at line 33 of file main.c.
Referenced by InitInMatrix(), InitParticles_eq(), InitParticles_flux(), InitParticles_np(), InitParticles_ones(), and InitPos().
nzone_in
unsigned int nzone_in
number of nodes in in-flow boundary face/zone
Definition at line 35 of file main.c.
Referenced by InitCell(), InitPos(), and ReadBoundaryNodes().
particle
struct contam* particle
DYNAMIC ARRAY OF PARTICLES
Definition at line 41 of file main.c.
Referenced by AcrossIntersection(), CalculateCurrentDT(), CalculateLagrangian(), CalculatePosition3D(), CalculateVelocity3D(), CalculateWeights(), ChangeFracture(), CheckDistance(), CheckNewCell(), CorrectorStep(), FinalPosition(), FlowInWeight(), InitInMatrix(), InitParticles_eq(), InitParticles_flux(), InitParticles_np(), InitParticles_ones(), InitPos(), InOutFlowCell(), InsideCell(), main(), Moving2Center(), Moving2NextCell(), Moving2NextCellBound(), NeighborCells(), PredictorStep(), SearchNeighborCells(), TimeDomainRW(), Xindex(), and Yindex().
pflotran
unsigned int pflotran
pflotran=1 when PFLOTRAN flow solver is used
Definition at line 27 of file main.c.
Referenced by DarcyVelocity(), HalfPolygonVelocity(), and ReadDataFiles().
porosity
double porosity
Fracture porosity, used in velocity reconstructions, defined by user
Definition at line 46 of file main.c.
Referenced by main(), VelocityExteriorNode(), and VelocityInteriorNode().
saturation
double saturation
Flow saturation, defined by user
Definition at line 50 of file main.c.
Referenced by main().
thickness
double thickness
One value for all fractures aperture (defined by user), used in case when fracture aperture is not provided by user
Definition at line 49 of file main.c.
Referenced by main(), and ReadDataFiles().
timesteps
unsigned long int timesteps
Max number of time steps used for each particles movements, defined by user
Definition at line 48 of file main.c.
Referenced by main(), and ParticleTrack().
timeunit
double timeunit
Time unit multiplier, converts calculated time/velocities according to required time units
Definition at line 51 of file main.c.
Referenced by main(), OutputMarPlumDisp(), ParticleTrack(), TimeFromMatrix(), VelocityExteriorNode(), and VelocityInteriorNode().
totalFluxIn
double totalFluxIn
Total Flow flux on in-flow boundary, calculated in the code
Definition at line 52 of file main.c.
Referenced by InitPos(), and ReadBoundaryNodes().