.TH "contam" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contam
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FuncDef\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvelocity\fP [2]"
.br
.ti -1c
.RI "double \fBposition\fP [2]"
.br
.ti -1c
.RI "double \fBprev_pos\fP [2]"
.br
.ti -1c
.RI "unsigned int \fBfracture\fP"
.br
.ti -1c
.RI "unsigned int \fBcell\fP"
.br
.ti -1c
.RI "unsigned int \fBintcell\fP"
.br
.ti -1c
.RI "double \fBweight\fP [3]"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.ti -1c
.RI "double \fBfl_weight\fP"
.br
.ti -1c
.RI "double \fBpressure\fP"
.br
.ti -1c
.RI "double \fBt_adv_diff\fP"
.br
.ti -1c
.RI "double \fBt_diff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
contam structure contains all parameters of the particles 
.PP
Definition at line 177 of file FuncDef\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int contam::cell"
the cell ID where particle is located at current time step 
.PP
Definition at line 192 of file FuncDef\&.h\&.
.SS "double contam::fl_weight"
weight of particle according to flow fluxes in in-flow boundary or according to initial fracture/cell aperture 
.PP
Definition at line 204 of file FuncDef\&.h\&.
.SS "unsigned int contam::fracture"
the fracture ID where particle is located at current time step 
.PP
Definition at line 189 of file FuncDef\&.h\&.
.SS "unsigned int contam::intcell"
intcell=1 if cell is on intersection; =0 if not 
.PP
Definition at line 195 of file FuncDef\&.h\&.
.SS "double contam::position[2]"
x and y particle position on fracture 
.PP
Definition at line 183 of file FuncDef\&.h\&.
.SS "double contam::pressure"
interpolated fluid pressure at particles location 
.PP
Definition at line 207 of file FuncDef\&.h\&.
.SS "double contam::prev_pos[2]"
x and y particle position in previous time step 
.PP
Definition at line 186 of file FuncDef\&.h\&.
.SS "double contam::t_adv_diff"
in case of TDRW: total travel time = advection plus diffusion 
.PP
Definition at line 210 of file FuncDef\&.h\&.
.SS "double contam::t_diff"
in case of TDRW: accumulative diffusion time 
.PP
Definition at line 213 of file FuncDef\&.h\&.
.SS "double contam::time"
accumulated advective time of particles movement 
.PP
Definition at line 201 of file FuncDef\&.h\&.
.SS "double contam::velocity[2]"
velocity of particle, interpolated from triangular cell 
.PP
Definition at line 180 of file FuncDef\&.h\&.
.SS "double contam::weight[3]"
weights, that are calculated for velocity interpolation from cell vertices 
.PP
Definition at line 198 of file FuncDef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
