.TH "element" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
element
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FuncDef\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBfracture\fP"
.br
.ti -1c
.RI "unsigned int \fBnode_ind\fP [3]"
.br
.ti -1c
.RI "unsigned int \fBveloc_ind\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file FuncDef\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int element::fracture"
fracture ID where cell is located 
.PP
Definition at line 164 of file FuncDef\&.h\&.
.SS "unsigned int element::node_ind[3]"
vertices ID (node indices) 
.PP
Definition at line 167 of file FuncDef\&.h\&.
.SS "unsigned int element::veloc_ind[3]"
index of reconstructed velocities at each vertex (index in vertex structure) 
.PP
Definition at line 170 of file FuncDef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
