.TH "inpfile" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inpfile
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBfilename\fP [120]"
.br
.ti -1c
.RI "long int \fBflag\fP"
.br
.ti -1c
.RI "double \fBparam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
reading file name from input dfnTrans control file 
.PP
Definition at line 10 of file InitialPartPositions\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char inpfile::filename"

.PP
Definition at line 11 of file InitialPartPositions\&.c\&.
.SS "long int inpfile::flag"

.PP
Definition at line 12 of file InitialPartPositions\&.c\&.
.SS "double inpfile::param"

.PP
Definition at line 13 of file InitialPartPositions\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
