.TH "lagrangian" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lagrangian
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtau\fP"
.br
.ti -1c
.RI "double \fBbetta\fP"
.br
.ti -1c
.RI "double \fBinitx\fP"
.br
.ti -1c
.RI "double \fBinity\fP"
.br
.ti -1c
.RI "double \fBinitz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
data structure of Lagrangian variables 
.PP
Definition at line 18 of file TrackingPart\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "double lagrangian::betta"

.PP
Definition at line 21 of file TrackingPart\&.c\&.
.SS "double lagrangian::initx"

.PP
Definition at line 22 of file TrackingPart\&.c\&.
.SS "double lagrangian::inity"

.PP
Definition at line 23 of file TrackingPart\&.c\&.
.SS "double lagrangian::initz"

.PP
Definition at line 24 of file TrackingPart\&.c\&.
.SS "double lagrangian::tau"

.PP
Definition at line 20 of file TrackingPart\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
