.TH "lb" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lb
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBlength_b\fP"
.br
.ti -1c
.RI "double \fBangle\fP"
.br
.ti -1c
.RI "double \fBnorm\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
lb is used in matrix calculation of linear least square 
.PP
Definition at line 9 of file VelocityReconstruction\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "double lb::angle"

.PP
Definition at line 11 of file VelocityReconstruction\&.c\&.
.SS "double lb::length_b"

.PP
Definition at line 10 of file VelocityReconstruction\&.c\&.
.SS "double lb::norm[2]"

.PP
Definition at line 12 of file VelocityReconstruction\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
