.TH "Docs_PT/ParticleTracking_source/output.c" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Docs_PT/ParticleTracking_source/output.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <search\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'FuncDef\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinpfile\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBOutputMarPlumDisp\fP (int currentnum, char path[125])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void OutputMarPlumDisp (int currentnum, char path[125])"
This function is used when particles trajectories should be output in format that MARFA and/or PLUMECALC codes will be able to read and process\&. 
.PP
Definition at line 19 of file output\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
