.TH "posit3d" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
posit3d
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBcord3\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure is used to calculate particle's position at 2D fracture plane to 3D simulation domain 
.PP
Definition at line 16 of file InitialPartPositions\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "double posit3d::cord3"

.PP
Definition at line 17 of file InitialPartPositions\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
