.TH "Docs_PT/ParticleTracking_source/ReadGridInit.c" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Docs_PT/ParticleTracking_source/ReadGridInit.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <search\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'FuncDef\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinpfile\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBReadInit\fP ()"
.br
.ti -1c
.RI "void \fBReadDataFiles\fP ()"
.br
.ti -1c
.RI "void \fBAdjacentCells\fP (int ln, int in, int jn, int kn)"
.br
.ti -1c
.RI "void \fBReadBoundaryNodes\fP ()"
.br
.ti -1c
.RI "FILE * \fBOpenFile\fP (char filen[120], char fileopt[2])"
.br
.ti -1c
.RI "void \fBReadPFLOTRANfile\fP (int nedges)"
.br
.ti -1c
.RI "void \fBReadFEHMfile\fP (int nedges)"
.br
.ti -1c
.RI "void \fBWritingInit\fP ()"
.br
.ti -1c
.RI "void \fBCheckGrid\fP ()"
.br
.ti -1c
.RI "struct \fBinpfile\fP \fBControl_File\fP (char fileobject[], int ctr)"
.br
.ti -1c
.RI "struct \fBinpfile\fP \fBControl_File_Optional\fP (char fileobject[], int ctr)"
.br
.ti -1c
.RI "int \fBString_Compare\fP (char string1[], char string2[])"
.br
.ti -1c
.RI "struct \fBinpfile\fP \fBControl_Data\fP (char fileobject[], int ctr)"
.br
.ti -1c
.RI "struct \fBinpfile\fP \fBControl_Param\fP (char fileobject[], int ctr)"
.br
.ti -1c
.RI "void \fBReadAperture\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void AdjacentCells (int ln, int in, int jn, int kn)"
The function defines adjacent triangular cells for each node 
.PP
Definition at line 540 of file ReadGridInit\&.c\&.
.SS "void CheckGrid ()"
The function checks the grid: looking for nodes that are defined as internal or external, but belong to two fractures and should be defined as interface nodes 
.PP
Definition at line 1055 of file ReadGridInit\&.c\&.
.SS "struct \fBinpfile\fP Control_Data (char fileobject[], int ctr)"
The function reads control file with input parameters to dfnTrans; returns input parameter value\&. If the parameter is not defined in the control file, the program is terminated\&. 
.PP
Definition at line 1201 of file ReadGridInit\&.c\&.
.SS "struct \fBinpfile\fP Control_File (char fileobject[], int ctr)"
The function reads control file with input parameters to dfnTrans; returns the file name and/or input parameter value\&. If the parameter is not defined in the control file, the program is terminated\&. 
.PP
Definition at line 1090 of file ReadGridInit\&.c\&.
.SS "struct \fBinpfile\fP Control_File_Optional (char fileobject[], int ctr)"
The function reads control file with input parameters to dfnTrans; returns the file name and/or input parameter value\&. This function is called for the optional parameters only\&. If the parameter is not defined in the control file, the default value is used\&. 
.PP
Definition at line 1135 of file ReadGridInit\&.c\&.
.SS "struct \fBinpfile\fP Control_Param (char fileobject[], int ctr)"
The function reads control file with input parameters to dfnTrans; returns input parameter value\&. If the parameter is not defined in the control file, the program is terminated\&. 
.PP
Definition at line 1245 of file ReadGridInit\&.c\&.
.SS "FILE* OpenFile (char filen[120], char fileopt[2])"
The function opens file for reading or writing\&. If error - the program is terminated\&. 
.PP
Definition at line 728 of file ReadGridInit\&.c\&.
.SS "void ReadAperture ()"
The function reads apertures of fractures in DFN\&. Aperture can be defined for each fracture or for every node/cell, representing internal heterogeneity\&. 
.PP
Definition at line 1289 of file ReadGridInit\&.c\&.
.SS "void ReadBoundaryNodes ()"
The functions reads node's IDs assigned to in-flow and out-flow boundaries\&. the total input flow flux is calculated\&. 
.PP
Definition at line 581 of file ReadGridInit\&.c\&.
.SS "void ReadDataFiles ()"
The function reads DFN mesh from inp and stor files if no aperture file specified, the aperture of all fractures will be equal to thickness value 
.PP
Definition at line 180 of file ReadGridInit\&.c\&.
.SS "void ReadFEHMfile (int nedges)"
The function opens and reads FEHM outputs; read in flow fluxes and cell volumes\&. 
.PP
Definition at line 879 of file ReadGridInit\&.c\&.
.SS "void ReadInit ()"
The function reads total number of nodes, triangular cells, fractures in DFN mesh\&. The memory is allocated for data structures: NODE, CELL, FRACTURE 
.PP
Definition at line 16 of file ReadGridInit\&.c\&.
.SS "void ReadPFLOTRANfile (int nedges)"
The function opens and reads PFLOTRAN files, read in flow fluxes, areas, pressure\&. 
.PP
Definition at line 742 of file ReadGridInit\&.c\&.
.SS "int String_Compare (char string1[], char string2[])"
The finction performs a string comparison, used in the control file reading\&. 
.PP
Definition at line 1176 of file ReadGridInit\&.c\&.
.SS "void WritingInit ()"
Functions write the data structure of nodes, cells and fractures into files in ASCII format with detail explanations\&. This output is optional and can be helpful in code debugging\&. 
.PP
Definition at line 981 of file ReadGridInit\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
