.TH "Docs_PT/ParticleTracking_source/TrackingPart.c" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Docs_PT/ParticleTracking_source/TrackingPart.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <search\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'FuncDef\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinpfile\fP"
.br
.ti -1c
.RI "struct \fBlagrangian\fP"
.br
.ti -1c
.RI "struct \fBintcoef\fP"
.br
.ti -1c
.RI "struct \fBposit3d\fP"
.br
.ti -1c
.RI "struct \fBtempout\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBParticleTrack\fP ()"
.br
.ti -1c
.RI "void \fBCheckNewCell\fP ()"
.br
.ti -1c
.RI "struct \fBintcoef\fP \fBCalculateWeights\fP (int nn1, int nn2, int nn3)"
.br
.ti -1c
.RI "void \fBSearchNeighborCells\fP (int nn1, int nn2, int nn3)"
.br
.ti -1c
.RI "int \fBInsideCell\fP (unsigned int numc)"
.br
.ti -1c
.RI "void \fBPredictorStep\fP ()"
.br
.ti -1c
.RI "void \fBCorrectorStep\fP ()"
.br
.ti -1c
.RI "void \fBNeighborCells\fP (int k)"
.br
.ti -1c
.RI "void \fBDefineTimeStep\fP ()"
.br
.ti -1c
.RI "int \fBCheckDistance\fP ()"
.br
.ti -1c
.RI "double \fBInOutFlowCell\fP (int indcell, int int1, double nposx, double nposy)"
.br
.ti -1c
.RI "void \fBAcrossIntersection\fP (int prevcell, int int1, int int2, int \fBmixing_rule\fP)"
.br
.ti -1c
.RI "int \fBStreamlineRandomSampling\fP (double products[4], double speedsq[4], int indj, int int1, int indk, int neighborcellind[4], int neighborfracind[4], int prevfrac, int prevcell)"
.br
.ti -1c
.RI "int \fBCompleteMixingRandomSampling\fP (double products[4], double speedsq[4], int indj, int int1, int indk)"
.br
.ti -1c
.RI "void \fBMoving2Center\fP (int nnp, int cellnumber)"
.br
.ti -1c
.RI "int \fBMoving2NextCell\fP (int stuck, int k)"
.br
.ti -1c
.RI "double \fBCalculateCurrentDT\fP ()"
.br
.ti -1c
.RI "int \fBXindex\fP (int nodenum, int nnp)"
.br
.ti -1c
.RI "int \fBYindex\fP (int nodenum, int nnp)"
.br
.ti -1c
.RI "void \fBMoving2NextCellBound\fP (int prevcell)"
.br
.ti -1c
.RI "void \fBParticleOutput\fP (int currentt, int fract_p)"
.br
.ti -1c
.RI "void \fBFinalPosition\fP ()"
.br
.ti -1c
.RI "struct \fBlagrangian\fP \fBCalculateLagrangian\fP (double xcurrent, double ycurrent, double zcurrent, double xprev, double yprev, double zprev)"
.br
.ti -1c
.RI "double \fBTimeDomainRW\fP (double time_advect)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBlagrangian\fP \fBlagvariable\fP"
.br
.ti -1c
.RI "unsigned int \fBFLAG_OUT\fP =0"
.br
.ti -1c
.RI "unsigned int \fBall_out\fP =0"
.br
.ti -1c
.RI "unsigned int \fBnp\fP"
.br
.ti -1c
.RI "unsigned int \fBt\fP"
.br
.ti -1c
.RI "unsigned int \fBnodeID\fP =0"
.br
.ti -1c
.RI "unsigned int \fBavs_o\fP =0"
.br
.ti -1c
.RI "unsigned int \fBtraj_o\fP =0"
.br
.ti -1c
.RI "unsigned int \fBcurv_o\fP =0"
.br
.ti -1c
.RI "unsigned int \fBno_out\fP =0"
.br
.ti -1c
.RI "unsigned int \fBtdrw\fP =0"
.br
.ti -1c
.RI "unsigned int \fBmixing_rule\fP =1"
.br
.ti -1c
.RI "unsigned int \fBmarfa\fP =0"
.br
.ti -1c
.RI "unsigned int \fBplumec\fP =0"
.br
.ti -1c
.RI "unsigned int \fBdisp_o\fP =0"
.br
.ti -1c
.RI "unsigned int \fBtimecounter\fP =0"
.br
.ti -1c
.RI "unsigned int \fBfrac_o\fP =0"
.br
.ti -1c
.RI "unsigned int \fBtfile\fP =0"
.br
.ti -1c
.RI "unsigned int \fBtdrw_o\fP =0"
.br
.ti -1c
.RI "double \fBtdrw_porosity\fP =0\&.0"
.br
.ti -1c
.RI "double \fBtdrw_diffcoeff\fP =0\&.0"
.br
.ti -1c
.RI "double \fBt_adv0\fP =0\&.0"
.br
.ti -1c
.RI "double \fBt_adv\fP =0\&.0"
.br
.ti -1c
.RI "double \fBtimediff\fP =0\&.0"
.br
.ti -1c
.RI "struct \fBtempout\fP * \fBtempdata\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void AcrossIntersection (int prevcell, int int1, int int2, int mixing_rule)"
Particle is moving through intersection line 
.PP
Definition at line 2013 of file TrackingPart\&.c\&.
.SS "double CalculateCurrentDT ()"
Functions returns particle instanteneous time step 
.PP
Definition at line 2527 of file TrackingPart\&.c\&.
.SS "struct \fBlagrangian\fP CalculateLagrangian (double xcurrent, double ycurrent, double zcurrent, double xprev, double yprev, double zprev)"
Function calculates Lagrangian variables: tau and beta\&. 
.PP
Definition at line 3140 of file TrackingPart\&.c\&.
.SS "struct \fBintcoef\fP CalculateWeights (int nn1, int nn2, int nn3)"
Function calculates interpolation weights for velocity instanteneous particles velocity and time step\&. 
.PP
Definition at line 1416 of file TrackingPart\&.c\&.
.SS "int CheckDistance ()"
Function checks the distance from particle to intersection line when particles is located at the intersection triangular cell 
.PP
Definition at line 1655 of file TrackingPart\&.c\&.
.SS "void CheckNewCell ()"
Function performs a check, did particle move to a new triangular cell during last time step or stayed at the same cell 
.PP
Definition at line 1273 of file TrackingPart\&.c\&.
.SS "int CompleteMixingRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk)"
Particle motion at a fracture intersection is determined by the streamline routing rule Arg 1: Cross product to define outgoing and incoming cells\&. Vector contains value for each cell at the intersection Arg 2: Vector of the speed squared for each cell at the intersection Arg 3: index of current cell in int1 node list Arg 4: int1 is the index of the node of the incoming cell that lies on the intersection Arg 5: indk gives the position in the list of the 4 intersection cells that is previous cell Return: The Exit cell at the intersection 
.PP
Definition at line 2344 of file TrackingPart\&.c\&.
.SS "void CorrectorStep ()"
Corrector step in Predictor-Corrector technique\&. Function calculates new particle position using calculated velocity in Predictor step\&. 
.PP
Definition at line 1576 of file TrackingPart\&.c\&.
.SS "void DefineTimeStep ()"
Function performs a loop through all the nodes in the mesh and defines a time step at each node\&. The time step of particles will be interpolated from time steps defined at each node\&. 
.PP
Definition at line 1622 of file TrackingPart\&.c\&.
.SS "void FinalPosition ()"
Function calculates particles final position at out-flow boundary 
.PP
Definition at line 2996 of file TrackingPart\&.c\&.
.SS "double InOutFlowCell (int indcell, int int1, double nposx, double nposy)"
Function defines if velocities on cell vertices pointing in or out of intersection line 
.PP
Definition at line 1949 of file TrackingPart\&.c\&.
.SS "int InsideCell (unsigned int numc)"
Function checks if particle is in the cell (numc is cell ID) 
.PP
Definition at line 1487 of file TrackingPart\&.c\&.
.SS "void Moving2Center (int nnp, int cellnumber)"
Function moves particle to the center of the same cell 
.PP
Definition at line 2440 of file TrackingPart\&.c\&.
.SS "int Moving2NextCell (int stuck, int k)"
Functions performs the movement of particle from one cell to the center of neighbouring cell\&. 
.PP
Definition at line 2471 of file TrackingPart\&.c\&.
.SS "void Moving2NextCellBound (int prevcell)"
In the pathological rare case, when particle is out of fracture, the function is called and it's moving particle to internal cell 
.PP
Definition at line 2572 of file TrackingPart\&.c\&.
.SS "void NeighborCells (int k)"
Function checks neighboring cells to find a particle 
.PP
Definition at line 1600 of file TrackingPart\&.c\&.
.SS "void ParticleOutput (int currentt, int fract_p)"
The function of particles trajectories outputs\&. Function is called at every intersection and outputs to file at each segment of particles trajectory: from intersection to intersection\&. The curvature of the trajectory is defined and dictate number of time steps for outputs (unless user requested every time step output)\&. 
.PP
Definition at line 2669 of file TrackingPart\&.c\&.
.SS "void ParticleTrack ()"
The main driving function of particles tracking procedure\&.
.IP "1." 4
The all necessary options for particle tracking and for the outputs are read from input control file\&.
.IP "2." 4
The subroutine for particle initial positions is called\&.
.IP "3." 4
External loop on paticles is organised\&. One particle at a time\&.
.IP "4." 4
Internal loop on time steps, where particles are mobing through fracture network\&. 4\&.1 Predictor -corrector technique is used for particles to move through fractures\&. 4\&.2 Complete mixing or streamline routing rule (defined by user) are used on intersections\&. 4\&.3 Particles data outputs\&. 
.PP

.PP
Definition at line 66 of file TrackingPart\&.c\&.
.SS "void PredictorStep ()"
Predictor step in Predictor-Corrector technique\&. Function calculates new velocities and new particle position\&. 
.PP
Definition at line 1541 of file TrackingPart\&.c\&.
.SS "void SearchNeighborCells (int nn1, int nn2, int nn3)"
Function performs a search of neighbouring cells of current particles position\&. 
.PP
Definition at line 1450 of file TrackingPart\&.c\&.
.SS "int StreamlineRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk, int neighborcellind[4], int neighborfracind[4], int prevfrac, int prevcell)"
Particle motion at a fracture intersection is determined by the streamline routing rule Arg 1: Cross product to define outgoing and incoming cells\&. Vector contains value for each cell at the intersection Arg 2: Vector of the speed squared for each cell at the intersection Arg 3: index of current cell in int1 node list Arg 4: int1 is the index of the node of the incoming cell that lies on the intersection Arg 5: indk gives the position in the list of the 4 intersection cells that is previous cell Arg 6: Vector of the indicies for the 4 neighboring cells Arg 7: Vector of the fracture index for the 4 neighboring cells Arg 8: Fracture a particle is coming from Arg 9: Cell index a particle is coming from Return: The Exit cell at the intersection 
.PP
Definition at line 2142 of file TrackingPart\&.c\&.
.SS "double TimeDomainRW (double time_advect)"
Time Domain Random Walk (TDRW) procedure\&. Returns a diffusion time of particle per racture\&. Called at each intersection\&. 
.PP
Definition at line 3175 of file TrackingPart\&.c\&.
.SS "int Xindex (int nodenum, int nnp)"
Functions returns the index of X coordination of intersection node 
.PP
Definition at line 2550 of file TrackingPart\&.c\&.
.SS "int Yindex (int nodenum, int nnp)"
Functions returns the index of Y coordination of intersection node 
.PP
Definition at line 2561 of file TrackingPart\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "unsigned int all_out =0"

.PP
Definition at line 29 of file TrackingPart\&.c\&.
.SS "unsigned int avs_o =0"

.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SS "unsigned int curv_o =0"

.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SS "unsigned int disp_o =0"

.PP
Definition at line 31 of file TrackingPart\&.c\&.
.SS "unsigned int FLAG_OUT =0"

.PP
Definition at line 29 of file TrackingPart\&.c\&.
.SS "unsigned int frac_o =0"

.PP
Definition at line 31 of file TrackingPart\&.c\&.
.SS "struct \fBlagrangian\fP lagvariable"

.PP
Definition at line 28 of file TrackingPart\&.c\&.
.SS "unsigned int marfa =0"

.PP
Definition at line 31 of file TrackingPart\&.c\&.
.SS "unsigned int mixing_rule =1"

.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SS "unsigned int no_out =0"

.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SS "unsigned int nodeID =0"

.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SS "unsigned int np"
index of current particle, idex in particle's loop 
.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SS "unsigned int plumec =0"

.PP
Definition at line 31 of file TrackingPart\&.c\&.
.SS "unsigned int t"

.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SS "double t_adv =0\&.0"

.PP
Definition at line 32 of file TrackingPart\&.c\&.
.SS "double t_adv0 =0\&.0"

.PP
Definition at line 32 of file TrackingPart\&.c\&.
.SS "unsigned int tdrw =0"

.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SS "double tdrw_diffcoeff =0\&.0"

.PP
Definition at line 32 of file TrackingPart\&.c\&.
.SS "unsigned int tdrw_o =0"

.PP
Definition at line 31 of file TrackingPart\&.c\&.
.SS "double tdrw_porosity =0\&.0"

.PP
Definition at line 32 of file TrackingPart\&.c\&.
.SS "struct \fBtempout\fP* tempdata"

.PP
Definition at line 56 of file TrackingPart\&.c\&.
.SS "unsigned int tfile =0"

.PP
Definition at line 31 of file TrackingPart\&.c\&.
.SS "unsigned int timecounter =0"

.PP
Definition at line 31 of file TrackingPart\&.c\&.
.SS "double timediff =0\&.0"

.PP
Definition at line 32 of file TrackingPart\&.c\&.
.SS "unsigned int traj_o =0"

.PP
Definition at line 30 of file TrackingPart\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
