
User Defined Fracture Generation Parameters
**************************************************

User defined deterministic features can be included into dfnWorks in a number of ways. There are two format options for ellipses and rectangles. One can also put in a selection of convex *n* vertex polygons.

.. include:: dfngen_docs/user_ellipses.inc

.. include:: dfngen_docs/user_rectangles.inc

.. include:: dfngen_docs/user_polygons.inc
