
User Defined Fracture Generation Parameters
**************************************************

User defined deterministic features can be included into dfnWorks in a number of ways. There are two format options for ellipses and rectangles. One can also put in a selection of convex *n* vertex polygons.

.. note:: To incoperate user fractures into the domain see functions add_user_fract and add_user_fract_from_file in :ref:`pydfnGen <dfnWorks-python-chapter-dfnGen>`. Information in this section provides additional information about parameters as well as information for adding user fractures from a predefined file. 

.. include:: dfngen_docs/user_ellipses.inc

.. include:: dfngen_docs/user_rectangles.inc

.. include:: dfngen_docs/user_polygons.inc
