.TH "intcoef" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intcoef
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBweights\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interpolation coefficients: barycentric interpolation is used to define instanteneous particle's velocity from Darcy velocities defined on triangular cell vertices\&. 
.PP
Definition at line 33 of file TrackingPart\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "double intcoef::weights[3]"

.PP
Definition at line 35 of file TrackingPart\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
