.TH "matr" 3 "Mon Jun 24 2019" "dfnTrans" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmatrinvG\fP [2][40]"
.br
.ti -1c
.RI "double \fBmatinv\fP [2][2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
matr is used in matrix calculation of linear least square 
.PP
Definition at line 15 of file VelocityReconstruction\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "double matr::matinv[2][2]"

.PP
Definition at line 17 of file VelocityReconstruction\&.c\&.
.SS "double matr::matrinvG[2][40]"

.PP
Definition at line 16 of file VelocityReconstruction\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dfnTrans from the source code\&.
