"""
.. module:: mesh_edfn.py
   :synopsis: Build a hex/tet matrix mesh around a meshed DFN and tag the DFN nodes with the containing matrix control volume
.. moduleauthor:: Jeffrey Hyman <jhyman@lanl.gov>

"""

import os
import sys


def write_edfn_lagrit_script(self, nx, ny, nz):
    """ Writes the LaGriT script build_hex_dfn.lgi for the hex+DFN workflow. Domain size and center are taken from the DFN object.

    Parameters
    ------------------
        self : DFN object

        nx, ny, nz : int
            Number of hex mesh nodes per axis

    Returns
    ---------------
        lagrit_file : str
            Name of the LaGriT script written to disk

    Notes
    --------------
        LaGriT define statements cannot do arithmetic, so the domain corners are computed here.

    """
    lx, ly, lz = self.domain['x'], self.domain['y'], self.domain['z']
    cx, cy, cz = self.params['domainCenter']['value']

    x0, x1 = cx - lx / 2.0, cx + lx / 2.0
    y0, y1 = cy - ly / 2.0, cy + ly / 2.0
    z0, z1 = cz - lz / 2.0, cz + lz / 2.0

    lagrit_file = "build_hex_dfn.lgi"

    lagrit_script = f"""# ---------------------------------------------------
# Auto-generated by pydfnworks mesh_edfn.py
# hex mesh -> tet conversion,
# DFN import, Voronoi node-ID tagging of DFN nodes,
# boundary zones, PFLOTRAN dump
# ---------------------------------------------------

# --- Domain extents ---
define / X0 / {x0:.12f}
define / X1 / {x1:.12f}
define / Y0 / {y0:.12f}
define / Y1 / {y1:.12f}
define / Z0 / {z0:.12f}
define / Z1 / {z1:.12f}

# --- Number of nodes per axis ---
define / NX / {nx}
define / NY / {ny}
define / NZ / {nz}

# --- Mesh object names ---
define / MOHEX / mohex
define / MOTET / motet
define / MODFN / modfn

# --- I/O filenames ---
define / DFN_FILE / full_mesh.inp
define / HEX_OUT / hex_mesh.inp
define / TET_OUT / tet_mesh.inp
define / DFN_OUT / dfn_mesh_tagged.inp
define / CV_OUT / matrix_cells.dat
define / MATRIX_PREFIX / matrix

# ---------------------------------------------------
# Build hex matrix mesh
# ---------------------------------------------------
cmo / create / MOHEX / / / hex

createpts / brick / xyz / NX NY NZ / X0 Y0 Z0 / X1 Y1 Z1 / 1 1 1

cmo / setatt / MOHEX / imt / 1 0 0 / 1
cmo / setatt / MOHEX / itetclr / 1 0 0 / 1
resetpts / itp

cmo / status / brief
cmo / printatt / MOHEX / -xyz- / minmax
quality

# ---------------------------------------------------
# Convert hex mesh to tet mesh
# (PFLOTRAN dump requires tets, not hex)
# ---------------------------------------------------
cmo / create / MOTET
copypts / MOTET / MOHEX
cmo / select / MOTET
filter 1 0 0
rmpoint / compress

cmo / setatt / MOTET / imt / 1 0 0 / 1
cmo / setatt / MOTET / itp / 1 0 0 / 0

sort / MOTET / index / ascending / ikey / xic yic zic
reorder / MOTET / ikey
cmo / DELATT / MOTET / ikey

connect / noadd
cmo / setatt / MOTET / itetclr / 1 0 0 / 1
resetpts / itp

cmo / set_id / MOTET / node / node_id

cmo / status / brief
cmo / printatt / MOTET / -xyz- / minmax
quality

# ---------------------------------------------------
# Read DFN mesh
# ---------------------------------------------------
read / avs / DFN_FILE / MODFN

cmo / status / brief
cmo / printatt / MODFN / -xyz- / minmax

# ---------------------------------------------------
# Tag DFN nodes with containing tet node's Voronoi cell ID
# ---------------------------------------------------
cmo / addatt / MODFN / cv_id / vint / scalar / nnodes
interpolate / voronoi / MODFN / cv_id / 1 0 0 / MOTET / node_id

cmo / printatt / MODFN / cv_id / minmax

# ---------------------------------------------------
# Dump inspection files
# ---------------------------------------------------
dump / avs2 / HEX_OUT / MOHEX
dump / avs2 / TET_OUT / MOTET
dump / avs2 / DFN_OUT / MODFN

# ---------------------------------------------------
# Dump cv_id per DFN node (hide the other node attributes)
# ---------------------------------------------------
cmo / select / MODFN
cmo / modatt / MODFN / isn / ioflag / l
cmo / modatt / MODFN / dfield / ioflag / l
cmo / modatt / MODFN / a_b / ioflag / l
cmo / modatt / MODFN / b_a / ioflag / l
cmo / modatt / MODFN / xnorm / ioflag / l
cmo / modatt / MODFN / ynorm / ioflag / l
cmo / modatt / MODFN / znorm / ioflag / l
cmo / modatt / MODFN / evol_one / ioflag / l
cmo / modatt / MODFN / evol_all / ioflag / l
cmo / modatt / MODFN / numbnd / ioflag / l
cmo / modatt / MODFN / id_numb / ioflag / l
cmo / modatt / MODFN / itp / ioflag / l
cmo / modatt / MODFN / icr / ioflag / l
cmo / modatt / MODFN / imt1 / ioflag / l
dump / avs2 / CV_OUT / MODFN / 0 0 2 0

# ---------------------------------------------------
# Matrix mesh: boundary zones and PFLOTRAN unstructured grid
# ---------------------------------------------------
cmo / select / MOTET
cmo / modatt / MOTET / itp / ioflag / l
cmo / modatt / MOTET / isn / ioflag / l
cmo / modatt / MOTET / icr / ioflag / l

dump / zone_outside / MATRIX_PREFIX / MOTET
dump / pflotran / MATRIX_PREFIX / MOTET / nofilter_zero

finish
"""

    with open(lagrit_file, "w") as fp:
        fp.write(lagrit_script)
        fp.flush()

    return lagrit_file


def mesh_edfn(self, nx, ny, nz):
    """ Builds a hex matrix mesh over the domain, converts it to tets, tags each DFN node with the
    ID of the tet node whose Voronoi cell contains it, and dumps the matrix boundary zones and
    PFLOTRAN .uge. The DFN must already be meshed (DFN.mesh_network()). Runs in the job directory.

    Parameters
    ------------------
        self : DFN object

        nx, ny, nz : int
            Number of hex mesh nodes per axis

    Returns
    ---------------
        None

    Notes
    --------------
        Output files: build_hex_dfn.lgi, hex_mesh.inp, tet_mesh.inp, dfn_mesh_tagged.inp,
        matrix_cells.dat (cv_id per DFN node), matrix_outside.zone, matrix.uge

    """
    self.print_log('=' * 80)
    self.print_log("Creating EDFN matrix mesh using LaGriT : Starting")
    self.print_log('=' * 80)

    if not os.path.isfile("full_mesh.inp"):
        error = "Error. full_mesh.inp not found. Mesh the DFN first (DFN.mesh_network()).\nExiting program."
        self.print_log(error, 'critical')
        sys.stderr.write(error)
        sys.exit(1)

    lagrit_file = self.write_edfn_lagrit_script(nx, ny, nz)
    self.run_lagrit(lagrit_file)

    self.print_log('=' * 80)
    self.print_log("Creating EDFN matrix mesh using LaGriT : Complete")
    self.print_log('=' * 80)
