"""
.. module:: mesh_edfn.py
   :synopsis: Build a hex/tet matrix mesh around a meshed DFN and tag the DFN nodes with the containing matrix control volume
.. moduleauthor:: Jeffrey Hyman <jhyman@lanl.gov>

"""

import os
import sys
import numpy as np


def write_edfn_lagrit_script(self, nx, ny, nz):
    """ Writes the LaGriT script build_hex_dfn.lgi for the hex+DFN workflow. Domain size and center are taken from the DFN object.

    Parameters
    ------------------
        self : DFN object

        nx, ny, nz : int
            Number of hex mesh nodes per axis

    Returns
    ---------------
        lagrit_file : str
            Name of the LaGriT script written to disk

    Notes
    --------------
        LaGriT define statements cannot do arithmetic, so the domain corners are computed here.

    """
    lx, ly, lz = self.domain['x'], self.domain['y'], self.domain['z']
    cx, cy, cz = self.params['domainCenter']['value']

    x0, x1 = cx - lx / 2.0, cx + lx / 2.0
    y0, y1 = cy - ly / 2.0, cy + ly / 2.0
    z0, z1 = cz - lz / 2.0, cz + lz / 2.0

    lagrit_file = "build_hex_dfn.lgi"

    lagrit_script = f"""# ---------------------------------------------------
# Auto-generated by pydfnworks mesh_edfn.py
# hex mesh -> tet conversion,
# DFN import, Voronoi node-ID tagging of DFN nodes,
# boundary zones, PFLOTRAN dump
# ---------------------------------------------------

# --- Domain extents ---
define / X0 / {x0:.12f}
define / X1 / {x1:.12f}
define / Y0 / {y0:.12f}
define / Y1 / {y1:.12f}
define / Z0 / {z0:.12f}
define / Z1 / {z1:.12f}

# --- Number of nodes per axis ---
define / NX / {nx}
define / NY / {ny}
define / NZ / {nz}

# --- Mesh object names ---
define / MOHEX / mohex
define / MOTET / motet
define / MODFN / modfn

# --- I/O filenames ---
define / DFN_FILE / full_mesh.inp
define / HEX_OUT / hex_mesh.inp
define / TET_OUT / tet_mesh.inp
define / DFN_OUT / dfn_mesh_tagged.inp
define / CV_OUT / matrix_cells.dat
define / MATRIX_PREFIX / matrix

# ---------------------------------------------------
# Build hex matrix mesh
# ---------------------------------------------------
cmo / create / MOHEX / / / hex

createpts / brick / xyz / NX NY NZ / X0 Y0 Z0 / X1 Y1 Z1 / 1 1 1

cmo / setatt / MOHEX / imt / 1 0 0 / 1
cmo / setatt / MOHEX / itetclr / 1 0 0 / 1
resetpts / itp

cmo / status / brief
cmo / printatt / MOHEX / -xyz- / minmax
quality

# ---------------------------------------------------
# Convert hex mesh to tet mesh
# (PFLOTRAN dump requires tets, not hex)
# ---------------------------------------------------
cmo / create / MOTET
copypts / MOTET / MOHEX
cmo / select / MOTET
filter 1 0 0
rmpoint / compress

cmo / setatt / MOTET / imt / 1 0 0 / 1
cmo / setatt / MOTET / itp / 1 0 0 / 0

sort / MOTET / index / ascending / ikey / xic yic zic
reorder / MOTET / ikey
cmo / DELATT / MOTET / ikey

connect / noadd
cmo / setatt / MOTET / itetclr / 1 0 0 / 1
resetpts / itp

cmo / set_id / MOTET / node / node_id

cmo / status / brief
cmo / printatt / MOTET / -xyz- / minmax
quality

# ---------------------------------------------------
# Read DFN mesh
# ---------------------------------------------------
read / avs / DFN_FILE / MODFN
cmo / set_id / MODFN / node / dfn_id

cmo / status / brief
cmo / printatt / MODFN / -xyz- / minmax

# ---------------------------------------------------
# Tag DFN nodes with containing tet node's Voronoi cell ID
# ---------------------------------------------------
cmo / addatt / MODFN / cv_id / vint / scalar / nnodes
interpolate / voronoi / MODFN / cv_id / 1 0 0 / MOTET / node_id

cmo / printatt / MODFN / cv_id / minmax

# ---------------------------------------------------
# Dump inspection files
# ---------------------------------------------------
dump / avs2 / HEX_OUT / MOHEX
dump / avs2 / TET_OUT / MOTET
dump / avs2 / DFN_OUT / MODFN

# ---------------------------------------------------
# Dump dfn_id, cv_id per DFN node (hide the other node attributes)
# ---------------------------------------------------
cmo / select / MODFN
cmo / modatt / MODFN / isn / ioflag / l
cmo / modatt / MODFN / dfield / ioflag / l
cmo / modatt / MODFN / a_b / ioflag / l
cmo / modatt / MODFN / b_a / ioflag / l
cmo / modatt / MODFN / xnorm / ioflag / l
cmo / modatt / MODFN / ynorm / ioflag / l
cmo / modatt / MODFN / znorm / ioflag / l
cmo / modatt / MODFN / evol_one / ioflag / l
cmo / modatt / MODFN / evol_all / ioflag / l
cmo / modatt / MODFN / numbnd / ioflag / l
cmo / modatt / MODFN / id_numb / ioflag / l
cmo / modatt / MODFN / itp / ioflag / l
cmo / modatt / MODFN / icr / ioflag / l
cmo / modatt / MODFN / imt1 / ioflag / l
dump / avs2 / CV_OUT / MODFN / 0 0 2 0

# ---------------------------------------------------
# Matrix mesh: boundary zones and PFLOTRAN unstructured grid
# ---------------------------------------------------
cmo / select / MOTET
cmo / modatt / MOTET / itp / ioflag / l
cmo / modatt / MOTET / isn / ioflag / l
cmo / modatt / MOTET / icr / ioflag / l

dump / zone_outside / MATRIX_PREFIX / MOTET
dump / pflotran / MATRIX_PREFIX / MOTET / nofilter_zero

finish
"""

    with open(lagrit_file, "w") as fp:
        fp.write(lagrit_script)
        fp.flush()

    return lagrit_file


def mesh_edfn(self, nx, ny, nz):
    """ Builds a hex matrix mesh over the domain, converts it to tets, tags each DFN node with the
    ID of the tet node whose Voronoi cell contains it, and dumps the matrix boundary zones and
    PFLOTRAN .uge. The DFN must already be meshed (DFN.mesh_network()). Runs in the job directory.

    Parameters
    ------------------
        self : DFN object

        nx, ny, nz : int
            Number of hex mesh nodes per axis

    Returns
    ---------------
        None

    Notes
    --------------
        Output files: build_hex_dfn.lgi, hex_mesh.inp, tet_mesh.inp, dfn_mesh_tagged.inp,
        matrix_cells.dat (dfn_id, cv_id per DFN node), matrix_to_dfn_nodes.dat (DFN nodes per matrix node),
        matrix_outside.zone, matrix.uge

    """
    self.print_log('=' * 80)
    self.print_log("Creating EDFN matrix mesh using LaGriT : Starting")
    self.print_log('=' * 80)

    if not os.path.isfile("full_mesh.inp"):
        error = "Error. full_mesh.inp not found. Mesh the DFN first (DFN.mesh_network()).\nExiting program."
        self.print_log(error, 'critical')
        sys.stderr.write(error)
        sys.exit(1)

    lagrit_file = self.write_edfn_lagrit_script(nx, ny, nz)
    self.run_lagrit(lagrit_file)
    self.process_edfn_output()

    self.print_log('=' * 80)
    self.print_log("Creating EDFN matrix mesh using LaGriT : Complete")
    self.print_log('=' * 80)


def process_edfn_output(self):
    """ Reads matrix_cells.dat (dfn_id, cv_id per DFN node) written by LaGriT, builds the inverse map
    from matrix node to the DFN nodes it contains, and writes it to matrix_to_dfn_nodes.dat.

    Parameters
    ------------------
        self : DFN object

    Returns
    ---------------
        None

    Notes
    --------------
        Sets self.edfn_dfn_to_matrix : numpy array, length num DFN nodes, entry i is the matrix node
        containing DFN node i+1 (1-based ids).
        Sets self.edfn_matrix_to_dfn : dict, matrix node id -> numpy array of DFN node ids.
        matrix_to_dfn_nodes.dat has three '#' header lines, then one line per matrix node that
        contains DFN nodes: matrix_id  num_dfn_nodes  dfn_id_1 dfn_id_2 ...

    """
    self.print_log("--> Processing EDFN output")

    with open("matrix_cells.dat", "r") as fp:
        fp.readline()  # avs header, node count is not filled in for attribute-only dumps
        num_att = int(fp.readline().split()[0])
        names = [fp.readline().split(",")[0].strip() for _ in range(num_att)]
        data = np.loadtxt(fp, dtype=int, ndmin=2)

    dfn_id = data[:, names.index("dfn_id")]
    cv_id = data[:, names.index("cv_id")]

    order = np.argsort(dfn_id)
    self.edfn_dfn_to_matrix = cv_id[order]

    self.edfn_matrix_to_dfn = {}
    for m in np.unique(cv_id):
        self.edfn_matrix_to_dfn[int(m)] = dfn_id[cv_id == m]

    with open("matrix_to_dfn_nodes.dat", "w") as fp:
        fp.write("# DFN nodes contained in each matrix (tet mesh) node's Voronoi cell\n")
        fp.write(f"# num_matrix_nodes {len(self.edfn_matrix_to_dfn)} num_dfn_nodes {len(dfn_id)}\n")
        fp.write("# matrix_id num_dfn_nodes dfn_id_1 dfn_id_2 ...\n")
        for m, nodes in self.edfn_matrix_to_dfn.items():
            fp.write(f"{m} {len(nodes)} " + " ".join(str(n) for n in nodes) + "\n")

    self.print_log(f"--> {len(dfn_id)} DFN nodes mapped into {len(self.edfn_matrix_to_dfn)} matrix nodes")
    self.print_log("--> Wrote matrix_to_dfn_nodes.dat")
