set(vtkCommonExecutionModel_HEADERS_LOADED 1)
set(vtkCommonExecutionModel_HEADERS "vtkAlgorithm;vtkAlgorithmOutput;vtkAnnotationLayersAlgorithm;vtkArrayDataAlgorithm;vtkCachedStreamingDemandDrivenPipeline;vtkCastToConcrete;vtkCompositeDataPipeline;vtkCompositeDataSetAlgorithm;vtkDataObjectAlgorithm;vtkDataSetAlgorithm;vtkDemandDrivenPipeline;vtkDirectedGraphAlgorithm;vtkEnsembleSource;vtkExecutive;vtkExtentSplitter;vtkExtentTranslator;vtkFilteringInformationKeyManager;vtkGraphAlgorithm;vtkHierarchicalBoxDataSetAlgorithm;vtkHyperOctreeAlgorithm;vtkHyperTreeGridAlgorithm;vtkImageAlgorithm;vtkImageInPlaceFilter;vtkImageProgressIterator;vtkImageToStructuredGrid;vtkImageToStructuredPoints;vtkInformationDataObjectMetaDataKey;vtkInformationExecutivePortKey;vtkInformationExecutivePortVectorKey;vtkInformationIntegerRequestKey;vtkMultiBlockDataSetAlgorithm;vtkMultiTimeStepAlgorithm;vtkPassInputTypeAlgorithm;vtkPiecewiseFunctionAlgorithm;vtkPiecewiseFunctionShiftScale;vtkPointSetAlgorithm;vtkPolyDataAlgorithm;vtkRectilinearGridAlgorithm;vtkScalarTree;vtkSimpleImageToImageFilter;vtkSimpleScalarTree;vtkSpanSpace;vtkStreamingDemandDrivenPipeline;vtkStructuredGridAlgorithm;vtkTableAlgorithm;vtkSMPProgressObserver;vtkThreadedCompositeDataPipeline;vtkThreadedImageAlgorithm;vtkTreeAlgorithm;vtkTrivialConsumer;vtkTrivialProducer;vtkUndirectedGraphAlgorithm;vtkUnstructuredGridAlgorithm;vtkUnstructuredGridBaseAlgorithm;vtkProgressObserver;vtkSelectionAlgorithm;vtkExtentRCBPartitioner;vtkUniformGridPartitioner;vtkUniformGridAMRAlgorithm;vtkOverlappingAMRAlgorithm;vtkNonOverlappingAMRAlgorithm")

foreach(header ${vtkCommonExecutionModel_HEADERS})
  set(vtkCommonExecutionModel_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkCommonExecutionModel_HEADER_vtkExecutive_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkHyperOctreeAlgorithm_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkHyperTreeGridAlgorithm_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkImageAlgorithm_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkImageInPlaceFilter_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkInformationExecutivePortKey_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkInformationExecutivePortVectorKey_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkScalarTree_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkSimpleImageToImageFilter_ABSTRACT 1)
set(vtkCommonExecutionModel_HEADER_vtkThreadedImageAlgorithm_ABSTRACT 1)

set(vtkCommonExecutionModel_HEADER_vtkFilteringInformationKeyManager_WRAP_EXCLUDE 1)
set(vtkCommonExecutionModel_HEADER_vtkImageProgressIterator_WRAP_EXCLUDE 1)
set(vtkCommonExecutionModel_HEADER_vtkSMPProgressObserver_WRAP_EXCLUDE 1)


