set(vtkCommonComputationalGeometry_HEADERS_LOADED 1)
set(vtkCommonComputationalGeometry_HEADERS "vtkCardinalSpline;vtkKochanekSpline;vtkParametricBoy;vtkParametricConicSpiral;vtkParametricCrossCap;vtkParametricDini;vtkParametricEllipsoid;vtkParametricEnneper;vtkParametricFigure8Klein;vtkParametricFunction;vtkParametricKlein;vtkParametricMobius;vtkParametricRandomHills;vtkParametricRoman;vtkParametricSpline;vtkParametricSuperEllipsoid;vtkParametricSuperToroid;vtkParametricTorus;vtkParametricKuen;vtkParametricPseudosphere;vtkParametricBohemianDome;vtkParametricHenneberg;vtkParametricCatalanMinimal;vtkParametricBour;vtkParametricPluckerConoid")

foreach(header ${vtkCommonComputationalGeometry_HEADERS})
  set(vtkCommonComputationalGeometry_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkCommonComputationalGeometry_HEADER_vtkParametricFunction_ABSTRACT 1)



