set(vtkDomainsChemistry_HEADERS_LOADED 1)
set(vtkDomainsChemistry_HEADERS "vtkBlueObeliskData;vtkBlueObeliskDataInternal;vtkBlueObeliskDataParser;vtkCMLMoleculeReader;vtkGaussianCubeReader2;vtkMoleculeAlgorithm;vtkMoleculeMapper;vtkMoleculeToAtomBallFilter;vtkMoleculeToBondStickFilter;vtkMoleculeToPolyDataFilter;vtkPeriodicTable;vtkProgrammableElectronicData;vtkProteinRibbonFilter;vtkSimpleBondPerceiver;vtkVASPAnimationReader;vtkVASPTessellationReader;vtkXYZMolReader2")

foreach(header ${vtkDomainsChemistry_HEADERS})
  set(vtkDomainsChemistry_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkDomainsChemistry_HEADER_vtkMoleculeToPolyDataFilter_ABSTRACT 1)

set(vtkDomainsChemistry_HEADER_vtkBlueObeliskData_WRAP_EXCLUDE 1)
set(vtkDomainsChemistry_HEADER_vtkBlueObeliskDataInternal_WRAP_EXCLUDE 1)
set(vtkDomainsChemistry_HEADER_vtkBlueObeliskDataParser_WRAP_EXCLUDE 1)

set(vtkDomainsChemistry_HEADER_vtkBlueObeliskDataInternal_WRAP_EXCLUDE_PYTHON 1)

