set(vtkDICOMParser_LOADED 1)
set(vtkDICOMParser_DEPENDS "vtksys")
set(vtkDICOMParser_LIBRARIES "vtkDICOMParser")
set(vtkDICOMParser_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Utilities/DICOMParser")
set(vtkDICOMParser_LIBRARY_DIRS "")
set(vtkDICOMParser_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkDICOMParser_WRAP_HIERARCHY_FILE "")
set(vtkDICOMParser_KIT "")
set(vtkDICOMParser_EXCLUDE_FROM_WRAPPING 1)

