set(vtkDomainsChemistryOpenGL2_LOADED 1)
set(vtkDomainsChemistryOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkCommonMath;vtkDomainsChemistry;vtkDomainsChemistry;vtkRenderingCore;vtkRenderingOpenGL2;vtkglew")
set(vtkDomainsChemistryOpenGL2_LIBRARIES "vtkDomainsChemistryOpenGL2")
set(vtkDomainsChemistryOpenGL2_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Domains/ChemistryOpenGL2")
set(vtkDomainsChemistryOpenGL2_LIBRARY_DIRS "")
set(vtkDomainsChemistryOpenGL2_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkDomainsChemistryOpenGL2_WRAP_HIERARCHY_FILE "")
set(vtkDomainsChemistryOpenGL2_KIT "vtkOpenGL")
set(vtkDomainsChemistryOpenGL2_IMPLEMENTS "vtkDomainsChemistry")

