set(vtkexpat_LOADED 1)
set(vtkexpat_DEPENDS "")
set(vtkexpat_LIBRARIES "vtkexpat")
set(vtkexpat_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/expat")
set(vtkexpat_LIBRARY_DIRS "")
set(vtkexpat_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkexpat_WRAP_HIERARCHY_FILE "")
set(vtkexpat_KIT "")
set(vtkexpat_EXCLUDE_FROM_WRAPPING 1)

