set(vtkFiltersModeling_HEADERS_LOADED 1)
set(vtkFiltersModeling_HEADERS "vtkAdaptiveSubdivisionFilter;vtkBandedPolyDataContourFilter;vtkButterflySubdivisionFilter;vtkDijkstraGraphGeodesicPath;vtkDijkstraImageGeodesicPath;vtkFillHolesFilter;vtkGeodesicPath;vtkGraphGeodesicPath;vtkLinearExtrusionFilter;vtkLinearSubdivisionFilter;vtkLoopSubdivisionFilter;vtkPolyDataPointSampler;vtkProjectedTexture;vtkQuadRotationalExtrusionFilter;vtkRibbonFilter;vtkRotationalExtrusionFilter;vtkRuledSurfaceFilter;vtkSelectEnclosedPoints;vtkSelectPolyData;vtkSpherePuzzleArrows;vtkSpherePuzzle;vtkSubdivideTetra;vtkOutlineFilter;vtkSectorSource;vtkVolumeOfRevolutionFilter")

foreach(header ${vtkFiltersModeling_HEADERS})
  set(vtkFiltersModeling_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkFiltersModeling_HEADER_vtkGeodesicPath_ABSTRACT 1)
set(vtkFiltersModeling_HEADER_vtkGraphGeodesicPath_ABSTRACT 1)



