set(vtkFiltersParallel_HEADERS_LOADED 1)
set(vtkFiltersParallel_HEADERS "vtkAngularPeriodicFilter;vtkCollectGraph;vtkCollectPolyData;vtkCollectTable;vtkCutMaterial;vtkDuplicatePolyData;vtkExtractCTHPart;vtkExtractPolyDataPiece;vtkExtractUnstructuredGridPiece;vtkExtractUserDefinedPiece;vtkPCellDataToPointData;vtkPExtractArraysOverTime;vtkPeriodicFilter;vtkPKdTree;vtkPLinearExtrusionFilter;vtkPMaskPoints;vtkPOutlineCornerFilter;vtkPOutlineFilter;vtkPOutlineFilterInternals;vtkPPolyDataNormals;vtkPProbeFilter;vtkPProjectSphereFilter;vtkPReflectionFilter;vtkPResampleFilter;vtkPSphereSource;vtkPYoungsMaterialInterface;vtkPassThroughFilter;vtkPieceRequestFilter;vtkPieceScalars;vtkPipelineSize;vtkProcessIdScalars;vtkRectilinearGridOutlineFilter;vtkTransmitPolyDataPiece;vtkTransmitStructuredDataPiece;vtkTransmitRectilinearGridPiece;vtkTransmitStructuredGridPiece;vtkTransmitUnstructuredGridPiece")

foreach(header ${vtkFiltersParallel_HEADERS})
  set(vtkFiltersParallel_HEADER_${header}_EXISTS 1)
endforeach()


set(vtkFiltersParallel_HEADER_vtkPOutlineFilterInternals_WRAP_EXCLUDE 1)

set(vtkFiltersParallel_HEADER_vtkPOutlineFilterInternals_WRAP_EXCLUDE_PYTHON 1)

