set(vtkFiltersGeometry_HEADERS_LOADED 1)
set(vtkFiltersGeometry_HEADERS "vtkCompositeDataGeometryFilter;vtkGeometryFilter;vtkHierarchicalDataSetGeometryFilter;vtkImageDataGeometryFilter;vtkImageDataToUniformGrid;vtkLinearToQuadraticCellsFilter;vtkProjectSphereFilter;vtkRectilinearGridGeometryFilter;vtkStructuredGridGeometryFilter;vtkStructuredPointsGeometryFilter;vtkUnstructuredGridGeometryFilter;vtkDataSetSurfaceFilter;vtkDataSetRegionSurfaceFilter;vtkAbstractGridConnectivity;vtkDataSetGhostGenerator;vtkRectilinearGridPartitioner;vtkStructuredAMRNeighbor;vtkStructuredAMRGridConnectivity;vtkStructuredGridConnectivity;vtkStructuredGridGhostDataGenerator;vtkStructuredGridPartitioner;vtkStructuredNeighbor;vtkUniformGridGhostDataGenerator")

foreach(header ${vtkFiltersGeometry_HEADERS})
  set(vtkFiltersGeometry_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkFiltersGeometry_HEADER_vtkAbstractGridConnectivity_ABSTRACT 1)
set(vtkFiltersGeometry_HEADER_vtkDataSetGhostGenerator_ABSTRACT 1)

set(vtkFiltersGeometry_HEADER_vtkStructuredAMRNeighbor_WRAP_EXCLUDE 1)
set(vtkFiltersGeometry_HEADER_vtkStructuredNeighbor_WRAP_EXCLUDE 1)


