set(vtkFiltersFlowPaths_HEADERS_LOADED 1)
set(vtkFiltersFlowPaths_HEADERS "vtkAbstractInterpolatedVelocityField;vtkAMRInterpolatedVelocityField;vtkCompositeInterpolatedVelocityField;vtkInterpolatedVelocityField;vtkStreamTracer;vtkModifiedBSPTree;vtkCellLocatorInterpolatedVelocityField;vtkTemporalStreamTracer;vtkParticleTracerBase;vtkParticleTracer;vtkStreaklineFilter;vtkParticlePathFilter;vtkTemporalInterpolatedVelocityField;vtkCachingInterpolatedVelocityField;vtkDashedStreamLine;vtkStreamLine;vtkStreamPoints;vtkStreamer")

foreach(header ${vtkFiltersFlowPaths_HEADERS})
  set(vtkFiltersFlowPaths_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkFiltersFlowPaths_HEADER_vtkAbstractInterpolatedVelocityField_ABSTRACT 1)
set(vtkFiltersFlowPaths_HEADER_vtkCompositeInterpolatedVelocityField_ABSTRACT 1)
set(vtkFiltersFlowPaths_HEADER_vtkParticleTracerBase_ABSTRACT 1)
set(vtkFiltersFlowPaths_HEADER_vtkStreamer_ABSTRACT 1)



