set(vtkFiltersCore_HEADERS_LOADED 1)
set(vtkFiltersCore_HEADERS "vtkAppendFilter;vtkAppendPolyData;vtkAppendSelection;vtkArrayCalculator;vtkAssignAttribute;vtkAttributeDataToFieldDataFilter;vtkBinCellDataFilter;vtkCellDataToPointData;vtkCleanPolyData;vtkClipPolyData;vtkCompositeDataProbeFilter;vtkConnectivityFilter;vtkContourFilter;vtkContourGrid;vtkContourHelper;vtkDataObjectGenerator;vtkDataObjectToDataSetFilter;vtkDataSetEdgeSubdivisionCriterion;vtkDataSetToDataObjectFilter;vtkDecimatePolylineFilter;vtkDecimatePro;vtkDelaunay2D;vtkDelaunay3D;vtkElevationFilter;vtkExecutionTimer;vtkFeatureEdges;vtkFieldDataToAttributeDataFilter;vtkFlyingEdges2D;vtkFlyingEdges3D;vtkFlyingEdgesPlaneCutter;vtkGlyph2D;vtkGlyph3D;vtkHedgeHog;vtkHull;vtkIdFilter;vtkMarchingCubes;vtkMarchingSquares;vtkMaskFields;vtkMaskPoints;vtkMaskPolyData;vtkMassProperties;vtkMergeDataObjectFilter;vtkMergeFields;vtkMergeFilter;vtkPointDataToCellData;vtkPolyDataConnectivityFilter;vtkPolyDataNormals;vtkProbeFilter;vtkQuadricClustering;vtkQuadricDecimation;vtkRearrangeFields;vtkResampleToImage;vtkResampleWithDataSet;vtkReverseSense;vtkSimpleElevationFilter;vtkSmoothPolyDataFilter;vtkStripper;vtkStructuredGridOutlineFilter;vtkSynchronizedTemplates2D;vtkSynchronizedTemplates3D;vtkSynchronizedTemplatesCutter3D;vtkTensorGlyph;vtkThreshold;vtkThresholdPoints;vtkTransposeTable;vtkTriangleFilter;vtkTubeFilter;vtkUnstructuredGridQuadricDecimation;vtkVectorDot;vtkVectorNorm;vtkWindowedSincPolyDataFilter;vtkCutter;vtkCompositeCutter;vtkGridSynchronizedTemplates3D;vtkRectilinearSynchronizedTemplates;vtkEdgeSubdivisionCriterion;vtkStreamingTessellator;vtkImplicitPolyDataDistance;vtkStreamerBase;vtkCenterOfMass;vtkImageAppend;vtkStructuredGridAppend;vtkAppendCompositeDataLeaves")

foreach(header ${vtkFiltersCore_HEADERS})
  set(vtkFiltersCore_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkFiltersCore_HEADER_vtkEdgeSubdivisionCriterion_ABSTRACT 1)
set(vtkFiltersCore_HEADER_vtkStreamerBase_ABSTRACT 1)

set(vtkFiltersCore_HEADER_vtkContourHelper_WRAP_EXCLUDE 1)


