set(vtkgl2ps_LOADED 1)
set(vtkgl2ps_DEPENDS "vtkpng;vtkzlib")
set(vtkgl2ps_LIBRARIES "vtkgl2ps")
set(vtkgl2ps_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/gl2ps")
set(vtkgl2ps_LIBRARY_DIRS "")
set(vtkgl2ps_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkgl2ps_WRAP_HIERARCHY_FILE "")
set(vtkgl2ps_KIT "")
set(vtkgl2ps_EXCLUDE_FROM_WRAPPING 1)

