set(vtkglew_LOADED 1)
set(vtkglew_DEPENDS "")
set(vtkglew_LIBRARIES "vtkglew")
set(vtkglew_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/glew")
set(vtkglew_LIBRARY_DIRS "")
set(vtkglew_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkglew_WRAP_HIERARCHY_FILE "")
set(vtkglew_KIT "")
set(vtkglew_EXCLUDE_FROM_WRAPPING 1)

