set(vtkGeovisCore_HEADERS_LOADED 1)
set(vtkGeovisCore_HEADERS "vtkCompassRepresentation;vtkCompassWidget;vtkGeoAdaptiveArcs;vtkGeoAlignedImageSource;vtkGeoArcs;vtkGeoAssignCoordinates;vtkGeoCamera;vtkGeoFileImageSource;vtkGeoFileTerrainSource;vtkGeoGlobeSource;vtkGeoGraticule;vtkGeoImageNode;vtkGeoInteractorStyle;vtkGeoProjection;vtkGeoProjectionSource;vtkGeoRandomGraphSource;vtkGeoSampleArcs;vtkGeoSource;vtkGeoSphereTransform;vtkGeoTerrain;vtkGeoTerrain2D;vtkGeoTerrainNode;vtkGeoTransform;vtkGeoTreeNode;vtkGeoTreeNodeCache;vtkGlobeSource;vtkGeoAlignedImageRepresentation")

foreach(header ${vtkGeovisCore_HEADERS})
  set(vtkGeovisCore_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkGeovisCore_HEADER_vtkGeoSource_ABSTRACT 1)



