set(vtkIOXML_HEADERS_LOADED 1)
set(vtkIOXML_HEADERS "vtkRTXMLPolyDataReader;vtkXMLCompositeDataReader;vtkXMLCompositeDataWriter;vtkXMLDataReader;vtkXMLDataSetWriter;vtkXMLFileReadTester;vtkXMLGenericDataObjectReader;vtkXMLHierarchicalBoxDataFileConverter;vtkXMLHierarchicalBoxDataReader;vtkXMLHierarchicalBoxDataWriter;vtkXMLHierarchicalDataReader;vtkXMLHyperOctreeReader;vtkXMLHyperOctreeWriter;vtkXMLImageDataReader;vtkXMLImageDataWriter;vtkXMLMultiBlockDataReader;vtkXMLMultiBlockDataWriter;vtkXMLMultiGroupDataReader;vtkXMLPDataReader;vtkXMLPImageDataReader;vtkXMLPolyDataReader;vtkXMLPolyDataWriter;vtkXMLPPolyDataReader;vtkXMLPRectilinearGridReader;vtkXMLPStructuredDataReader;vtkXMLPStructuredGridReader;vtkXMLPUnstructuredDataReader;vtkXMLPUnstructuredGridReader;vtkXMLReader;vtkXMLRectilinearGridReader;vtkXMLRectilinearGridWriter;vtkXMLStructuredDataReader;vtkXMLStructuredDataWriter;vtkXMLStructuredGridReader;vtkXMLStructuredGridWriter;vtkXMLUniformGridAMRReader;vtkXMLUniformGridAMRWriter;vtkXMLUnstructuredDataReader;vtkXMLUnstructuredDataWriter;vtkXMLUnstructuredGridReader;vtkXMLUnstructuredGridWriter;vtkXMLWriterC;vtkXMLWriter")

foreach(header ${vtkIOXML_HEADERS})
  set(vtkIOXML_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkIOXML_HEADER_vtkXMLCompositeDataReader_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLCompositeDataWriter_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLDataReader_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLPDataReader_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLPStructuredDataReader_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLPUnstructuredDataReader_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLReader_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLStructuredDataReader_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLStructuredDataWriter_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLUnstructuredDataReader_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLUnstructuredDataWriter_ABSTRACT 1)
set(vtkIOXML_HEADER_vtkXMLWriter_ABSTRACT 1)

set(vtkIOXML_HEADER_vtkXMLWriterC_WRAP_EXCLUDE 1)

set(vtkIOXML_HEADER_vtkXMLWriterC_WRAP_EXCLUDE_PYTHON 1)

