set(vtkIOCore_HEADERS_LOADED 1)
set(vtkIOCore_HEADERS "vtkAbstractParticleWriter;vtkArrayReader;vtkArrayWriter;vtkASCIITextCodec;vtkBase64InputStream;vtkBase64OutputStream;vtkBase64Utilities;vtkDataCompressor;vtkDelimitedTextWriter;vtkGlobFileNames;vtkInputStream;vtkJavaScriptDataWriter;vtkOutputStream;vtkSortFileNames;vtkTextCodec;vtkTextCodecFactory;vtkUTF16TextCodec;vtkUTF8TextCodec;vtkAbstractPolyDataReader;vtkWriter;vtkZLibDataCompressor;vtkArrayDataReader;vtkArrayDataWriter")

foreach(header ${vtkIOCore_HEADERS})
  set(vtkIOCore_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkIOCore_HEADER_vtkAbstractParticleWriter_ABSTRACT 1)
set(vtkIOCore_HEADER_vtkDataCompressor_ABSTRACT 1)
set(vtkIOCore_HEADER_vtkTextCodec_ABSTRACT 1)
set(vtkIOCore_HEADER_vtkAbstractPolyDataReader_ABSTRACT 1)
set(vtkIOCore_HEADER_vtkWriter_ABSTRACT 1)



