set(vtkInfovisLayout_HEADERS_LOADED 1)
set(vtkInfovisLayout_HEADERS "vtkArcParallelEdgeStrategy;vtkAreaLayout;vtkAreaLayoutStrategy;vtkAssignCoordinates;vtkAssignCoordinatesLayoutStrategy;vtkAttributeClustering2DLayoutStrategy;vtkBoxLayoutStrategy;vtkCirclePackFrontChainLayoutStrategy;vtkCirclePackLayout;vtkCirclePackLayoutStrategy;vtkCirclePackToPolyData;vtkCircularLayoutStrategy;vtkClustering2DLayoutStrategy;vtkCommunity2DLayoutStrategy;vtkConeLayoutStrategy;vtkConstrained2DLayoutStrategy;vtkCosmicTreeLayoutStrategy;vtkEdgeLayout;vtkEdgeLayoutStrategy;vtkFast2DLayoutStrategy;vtkForceDirectedLayoutStrategy;vtkGeoEdgeStrategy;vtkGeoMath;vtkGraphLayout;vtkGraphLayoutStrategy;vtkIncrementalForceLayout;vtkPassThroughEdgeStrategy;vtkPassThroughLayoutStrategy;vtkPerturbCoincidentVertices;vtkRandomLayoutStrategy;vtkSimple2DLayoutStrategy;vtkSimple3DCirclesStrategy;vtkSliceAndDiceLayoutStrategy;vtkSpanTreeLayoutStrategy;vtkSplineGraphEdges;vtkSquarifyLayoutStrategy;vtkStackedTreeLayoutStrategy;vtkTreeLayoutStrategy;vtkTreeMapLayout;vtkTreeMapLayoutStrategy;vtkTreeMapToPolyData;vtkTreeOrbitLayoutStrategy;vtkTreeRingToPolyData;vtkKCoreLayout")

foreach(header ${vtkInfovisLayout_HEADERS})
  set(vtkInfovisLayout_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkInfovisLayout_HEADER_vtkAreaLayoutStrategy_ABSTRACT 1)
set(vtkInfovisLayout_HEADER_vtkCirclePackLayoutStrategy_ABSTRACT 1)
set(vtkInfovisLayout_HEADER_vtkEdgeLayoutStrategy_ABSTRACT 1)
set(vtkInfovisLayout_HEADER_vtkGraphLayoutStrategy_ABSTRACT 1)
set(vtkInfovisLayout_HEADER_vtkTreeMapLayoutStrategy_ABSTRACT 1)



