set(vtkkwiml_LOADED 1)
set(vtkkwiml_DEPENDS "")
set(vtkkwiml_LIBRARIES "")
set(vtkkwiml_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Utilities/KWIML")
set(vtkkwiml_LIBRARY_DIRS "")
set(vtkkwiml_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkkwiml_WRAP_HIERARCHY_FILE "")
set(vtkkwiml_KIT "")
set(vtkkwiml_EXCLUDE_FROM_WRAPPING 1)

