set(vtklibproj4_LOADED 1)
set(vtklibproj4_DEPENDS "")
set(vtklibproj4_LIBRARIES "vtkproj4")
set(vtklibproj4_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/libproj4/vtklibproj4;/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/libproj4")
set(vtklibproj4_LIBRARY_DIRS "")
set(vtklibproj4_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtklibproj4_WRAP_HIERARCHY_FILE "")
set(vtklibproj4_KIT "")
set(vtklibproj4_EXCLUDE_FROM_WRAPPING 1)

