set(vtkMetaIO_LOADED 1)
set(vtkMetaIO_DEPENDS "vtkzlib")
set(vtkMetaIO_LIBRARIES "vtkmetaio")
set(vtkMetaIO_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Utilities/MetaIO/vtkmetaio;/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Utilities/MetaIO")
set(vtkMetaIO_LIBRARY_DIRS "")
set(vtkMetaIO_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkMetaIO_WRAP_HIERARCHY_FILE "")
set(vtkMetaIO_KIT "")
set(vtkMetaIO_EXCLUDE_FROM_WRAPPING 1)

