set(vtknetcdf_LOADED 1)
set(vtknetcdf_DEPENDS "vtkhdf5")
set(vtknetcdf_LIBRARIES "vtkNetCDF;vtkNetCDF_cxx")
set(vtknetcdf_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/netcdf/vtknetcdf/include;/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/netcdf/vtknetcdf;/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/netcdf")
set(vtknetcdf_LIBRARY_DIRS "")
set(vtknetcdf_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtknetcdf_WRAP_HIERARCHY_FILE "")
set(vtknetcdf_KIT "")
set(vtknetcdf_EXCLUDE_FROM_WRAPPING 1)

