set(vtkpng_LOADED 1)
set(vtkpng_DEPENDS "vtkzlib")
set(vtkpng_LIBRARIES "vtkpng")
set(vtkpng_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/png")
set(vtkpng_LIBRARY_DIRS "")
set(vtkpng_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkpng_WRAP_HIERARCHY_FILE "")
set(vtkpng_KIT "")
set(vtkpng_EXCLUDE_FROM_WRAPPING 1)

