set(vtkRenderingGL2PSOpenGL2_LOADED 1)
set(vtkRenderingGL2PSOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkRenderingCore;vtkRenderingOpenGL2;vtkRenderingOpenGL2;vtkRenderingOpenGL2;vtkgl2ps")
set(vtkRenderingGL2PSOpenGL2_LIBRARIES "vtkRenderingGL2PSOpenGL2")
set(vtkRenderingGL2PSOpenGL2_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Rendering/GL2PSOpenGL2")
set(vtkRenderingGL2PSOpenGL2_LIBRARY_DIRS "")
set(vtkRenderingGL2PSOpenGL2_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkRenderingGL2PSOpenGL2_WRAP_HIERARCHY_FILE "")
set(vtkRenderingGL2PSOpenGL2_KIT "")
set(vtkRenderingGL2PSOpenGL2_IMPLEMENTS "vtkRenderingOpenGL2")

