set(vtkRenderingContextOpenGL2_LOADED 1)
set(vtkRenderingContextOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkCommonTransforms;vtkImagingCore;vtkRenderingContext2D;vtkRenderingContext2D;vtkRenderingCore;vtkRenderingFreeType;vtkRenderingOpenGL2;vtkglew")
set(vtkRenderingContextOpenGL2_LIBRARIES "vtkRenderingContextOpenGL2")
set(vtkRenderingContextOpenGL2_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Rendering/ContextOpenGL2")
set(vtkRenderingContextOpenGL2_LIBRARY_DIRS "")
set(vtkRenderingContextOpenGL2_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkRenderingContextOpenGL2_WRAP_HIERARCHY_FILE "")
set(vtkRenderingContextOpenGL2_KIT "vtkOpenGL")
set(vtkRenderingContextOpenGL2_IMPLEMENTS "vtkRenderingContext2D")

