set(vtkRenderingVolumeOpenGL2_LOADED 1)
set(vtkRenderingVolumeOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkCommonSystem;vtkCommonTransforms;vtkFiltersCore;vtkFiltersGeneral;vtkFiltersSources;vtkImagingCore;vtkImagingMath;vtkRenderingCore;vtkRenderingOpenGL2;vtkRenderingVolume;vtkRenderingVolume;vtkglew;vtksys")
set(vtkRenderingVolumeOpenGL2_LIBRARIES "vtkRenderingVolumeOpenGL2")
set(vtkRenderingVolumeOpenGL2_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Rendering/VolumeOpenGL2")
set(vtkRenderingVolumeOpenGL2_LIBRARY_DIRS "")
set(vtkRenderingVolumeOpenGL2_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkRenderingVolumeOpenGL2_WRAP_HIERARCHY_FILE "")
set(vtkRenderingVolumeOpenGL2_KIT "vtkOpenGL")
set(vtkRenderingVolumeOpenGL2_IMPLEMENTS "vtkRenderingVolume")

