set(vtkRenderingLabel_HEADERS_LOADED 1)
set(vtkRenderingLabel_HEADERS "vtkLabeledDataMapper;vtkLabeledTreeMapDataMapper;vtkLabelHierarchyAlgorithm;vtkLabelHierarchyCompositeIterator;vtkLabelHierarchy;vtkLabelHierarchyIterator;vtkLabelPlacementMapper;vtkLabelPlacer;vtkLabelRenderStrategy;vtkLabelSizeCalculator;vtkFreeTypeLabelRenderStrategy;vtkDynamic2DLabelMapper;vtkPointSetToLabelHierarchy")

foreach(header ${vtkRenderingLabel_HEADERS})
  set(vtkRenderingLabel_HEADER_${header}_EXISTS 1)
endforeach()

set(vtkRenderingLabel_HEADER_vtkLabelHierarchyIterator_ABSTRACT 1)
set(vtkRenderingLabel_HEADER_vtkLabelRenderStrategy_ABSTRACT 1)



