set(vtkRenderingOpenGL2_LOADED 1)
set(vtkRenderingOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkCommonMath;vtkCommonSystem;vtkCommonTransforms;vtkIOImage;vtkImagingCore;vtkRenderingCore;vtkRenderingCore;vtkUtilitiesEncodeString;vtkglew;vtksys")
set(vtkRenderingOpenGL2_LIBRARIES "vtkRenderingOpenGL2")
set(vtkRenderingOpenGL2_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Rendering/OpenGL2")
set(vtkRenderingOpenGL2_LIBRARY_DIRS "")
set(vtkRenderingOpenGL2_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkRenderingOpenGL2_WRAP_HIERARCHY_FILE "")
set(vtkRenderingOpenGL2_KIT "vtkOpenGL")
set(vtkRenderingOpenGL2_IMPLEMENTS "vtkRenderingCore")

