set(vtkRenderingFreeType_LOADED 1)
set(vtkRenderingFreeType_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkFiltersGeneral;vtkRenderingCore;vtkRenderingCore;vtkfreetype")
set(vtkRenderingFreeType_LIBRARIES "vtkRenderingFreeType")
set(vtkRenderingFreeType_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Rendering/FreeType")
set(vtkRenderingFreeType_LIBRARY_DIRS "")
set(vtkRenderingFreeType_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkRenderingFreeType_WRAP_HIERARCHY_FILE "")
set(vtkRenderingFreeType_KIT "vtkRendering")
set(vtkRenderingFreeType_IMPLEMENTS "vtkRenderingCore")

