set(vtkRenderingContextOpenGL2_HEADERS_LOADED 1)
set(vtkRenderingContextOpenGL2_HEADERS "vtkOpenGLContextActor;vtkOpenGLContextBufferId;vtkOpenGLContextDevice2D;vtkOpenGLContextDevice3D;vtkOpenGLPropItem;vtkRenderingContextOpenGL2ObjectFactory")

foreach(header ${vtkRenderingContextOpenGL2_HEADERS})
  set(vtkRenderingContextOpenGL2_HEADER_${header}_EXISTS 1)
endforeach()


set(vtkRenderingContextOpenGL2_HEADER_vtkOpenGLContextBufferId_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL2_HEADER_vtkOpenGLContextDevice2D_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL2_HEADER_vtkOpenGLContextDevice3D_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL2_HEADER_vtkOpenGLPropItem_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL2_HEADER_vtkRenderingContextOpenGL2ObjectFactory_WRAP_EXCLUDE 1)

set(vtkRenderingContextOpenGL2_HEADER_vtkRenderingContextOpenGL2ObjectFactory_WRAP_EXCLUDE_PYTHON 1)

