set(vtksys_LOADED 1)
set(vtksys_DEPENDS "")
set(vtksys_LIBRARIES "vtksys")
set(vtksys_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Utilities/KWSys")
set(vtksys_LIBRARY_DIRS "")
set(vtksys_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtksys_WRAP_HIERARCHY_FILE "")
set(vtksys_KIT "")
set(vtksys_EXCLUDE_FROM_WRAPPING 1)

