set(vtktiff_LOADED 1)
set(vtktiff_DEPENDS "vtkjpeg;vtkzlib")
set(vtktiff_LIBRARIES "vtktiff")
set(vtktiff_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/tiff/vtktiff/libtiff;/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/tiff")
set(vtktiff_LIBRARY_DIRS "")
set(vtktiff_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtktiff_WRAP_HIERARCHY_FILE "")
set(vtktiff_KIT "")
set(vtktiff_EXCLUDE_FROM_WRAPPING 1)

