set(vtkUtilitiesEncodeString_LOADED 1)
set(vtkUtilitiesEncodeString_DEPENDS "")
set(vtkUtilitiesEncodeString_LIBRARIES "")
set(vtkUtilitiesEncodeString_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/Utilities/EncodeString")
set(vtkUtilitiesEncodeString_LIBRARY_DIRS "")
set(vtkUtilitiesEncodeString_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkUtilitiesEncodeString_WRAP_HIERARCHY_FILE "")
set(vtkUtilitiesEncodeString_KIT "")
set(vtkUtilitiesEncodeString_EXCLUDE_FROM_WRAPPING 1)

