set(vtkverdict_LOADED 1)
set(vtkverdict_DEPENDS "")
set(vtkverdict_LIBRARIES "verdict")
set(vtkverdict_INCLUDE_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/ThirdParty/verdict")
set(vtkverdict_LIBRARY_DIRS "")
set(vtkverdict_RUNTIME_LIBRARY_DIRS "/home/nknapp/dfnworks-main/inp_2_vtk/VTK-7.1.0/lib")
set(vtkverdict_WRAP_HIERARCHY_FILE "")
set(vtkverdict_KIT "")
set(vtkverdict_EXCLUDE_FROM_WRAPPING 1)

