/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-7.1
 * 
 * Declare the vtkEDLComposeFS string.
 *
 */
#ifndef __vtkEDLComposeFS_h
#define __vtkEDLComposeFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkEDLComposeFS;

#endif /* #ifndef __vtkEDLComposeFS_h */
