/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-7.1
 * 
 * Declare the vtkGlyph3DVS string.
 *
 */
#ifndef __vtkGlyph3DVS_h
#define __vtkGlyph3DVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGlyph3DVS;

#endif /* #ifndef __vtkGlyph3DVS_h */
