/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-7.1
 * 
 * Declare the vtkStickMapperVS string.
 *
 */
#ifndef __vtkStickMapperVS_h
#define __vtkStickMapperVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkStickMapperVS;

#endif /* #ifndef __vtkStickMapperVS_h */
