/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-7.1
 * 
 * Declare the vtkSobelGradientMagnitudePass1FS string.
 *
 */
#ifndef __vtkSobelGradientMagnitudePass1FS_h
#define __vtkSobelGradientMagnitudePass1FS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSobelGradientMagnitudePass1FS;

#endif /* #ifndef __vtkSobelGradientMagnitudePass1FS_h */
