
def write_lagrit_script(
    nx,
    ny,
    nz,
    lx,
    ly,
    lz,
    epsilon,
    dfn_file="full_mesh.inp",
    hex_out="hex_mesh.inp",
    tet_out="tet_mesh.inp",
    dfn_out="dfn_mesh_tagged.inp",
    pflotran_prefix="hex_mesh",
    zone_prefix="matrix",
    script_name="build_hex_dfn.lgi",
):
    """
    Write a LaGriT .lgi script for the hex+DFN prototype workflow.

    Parameters
    ----------
    nx, ny, nz : int
        Number of nodes per axis.
    lx, ly, lz : float
        Domain length (m) in x, y, z. Domain is centered at the origin.
    epsilon : float
        Boundary tolerance for zone selection. Must be well under half
        the smallest grid spacing (lx/(nx-1), etc.) or it will either
        miss boundary nodes or catch interior ones.
    dfn_file : str
        Input DFN mesh file (AVS format), e.g. dfnWorks's full_mesh.inp.
    hex_out, tet_out, dfn_out : str
        AVS output filenames for inspection.
    pflotran_prefix : str
        Prefix for the dump/pflotran .uge output.
    zone_prefix : str
        Prefix for the six boundary .zone files.
    script_name : str
        Output .lgi filename.

    Returns
    -------
    str
        The script_name written to disk.
    """
    x0, x1 = -lx / 2.0, lx / 2.0
    y0, y1 = -ly / 2.0, ly / 2.0
    z0, z1 = -lz / 2.0, lz / 2.0

    xmin, xmax = x0 + epsilon, x1 - epsilon
    ymin, ymax = y0 + epsilon, y1 - epsilon
    zmin, zmax = z0 + epsilon, z1 - epsilon

    script = f"""# ---------------------------------------------------
# Auto-generated by build_hex_dfn_lgi.py
# hex mesh centered at origin -> tet conversion,
# DFN import, Voronoi node-ID tagging of DFN nodes,
# boundary zones, PFLOTRAN dump
# ---------------------------------------------------

# --- Domain extents ---
define / X0 / {x0:.12f}
define / X1 / {x1:.12f}
define / Y0 / {y0:.12f}
define / Y1 / {y1:.12f}
define / Z0 / {z0:.12f}
define / Z1 / {z1:.12f}

# --- Boundary thresholds (X1 - epsilon etc, computed in Python) ---
define / XMIN / {xmin:.12f}
define / XMAX / {xmax:.12f}
define / YMIN / {ymin:.12f}
define / YMAX / {ymax:.12f}
define / ZMIN / {zmin:.12f}
define / ZMAX / {zmax:.12f}

# --- Number of nodes per axis ---
define / NX / {nx}
define / NY / {ny}
define / NZ / {nz}

# --- Mesh object names ---
define / MOHEX / mohex
define / MOTET / motet
define / MODFN / modfn

# --- I/O filenames ---
define / DFN_FILE / {dfn_file}
define / HEX_OUT / {hex_out}
define / TET_OUT / {tet_out}
define / DFN_OUT / {dfn_out}
define / PFLOTRAN_PREFIX / {pflotran_prefix}

# ---------------------------------------------------
# Build hex matrix mesh
# ---------------------------------------------------
cmo / create / MOHEX / / / hex

createpts / brick / xyz / NX NY NZ / X0 Y0 Z0 / X1 Y1 Z1 / 1 1 1

cmo / setatt / MOHEX / imt / 1 0 0 / 1
cmo / setatt / MOHEX / itetclr / 1 0 0 / 1
resetpts / itp

cmo / status / brief
cmo / printatt / MOHEX / -xyz- / minmax
quality

# ---------------------------------------------------
# Convert hex mesh to tet mesh
# (PFLOTRAN dump requires tets, not hex)
# ---------------------------------------------------
cmo / create / MOTET
copypts / MOTET / MOHEX
cmo / select / MOTET
filter 1 0 0
rmpoint / compress

cmo / setatt / MOTET / imt / 1 0 0 / 1
cmo / setatt / MOTET / itp / 1 0 0 / 0

sort / MOTET / index / ascending / ikey / xic yic zic
reorder / MOTET / ikey
cmo / DELATT / MOTET / ikey

connect / noadd
cmo / setatt / MOTET / itetclr / 1 0 0 / 1
resetpts / itp

cmo / set_id / MOTET / node / node_id

cmo / status / brief
cmo / printatt / MOTET / -xyz- / minmax
quality

# ---------------------------------------------------
# Read DFN mesh
# ---------------------------------------------------
read / avs / DFN_FILE / MODFN

cmo / status / brief
cmo / printatt / MODFN / -xyz- / minmax

# ---------------------------------------------------
# Tag DFN nodes with containing tet node's Voronoi cell ID
# ---------------------------------------------------
cmo / addatt / MODFN / cv_id / vint / scalar / nnodes
interpolate / voronoi / MODFN / cv_id / 1 0 0 / MOTET / node_id

cmo / printatt / MODFN / cv_id / minmax

# ---------------------------------------------------
# Boundary zones on the tet mesh, prefix {zone_prefix}_
# ---------------------------------------------------
cmo / select / MOTET

define / ZONE / 1
define / FOUT / {zone_prefix}_top
pset / p_top / attribute / zic / 1 0 0 / gt / ZMAX
pset / p_top / zone / FOUT / ascii / ZONE

define / ZONE / 2
define / FOUT / {zone_prefix}_bottom
pset / p_bottom / attribute / zic / 1 0 0 / lt / ZMIN
pset / p_bottom / zone / FOUT / ascii / ZONE

define / ZONE / 3
define / FOUT / {zone_prefix}_left
pset / p_left / attribute / xic / 1 0 0 / lt / XMIN
pset / p_left / zone / FOUT / ascii / ZONE

define / ZONE / 4
define / FOUT / {zone_prefix}_right
pset / p_right / attribute / xic / 1 0 0 / gt / XMAX
pset / p_right / zone / FOUT / ascii / ZONE

define / ZONE / 5
define / FOUT / {zone_prefix}_front
pset / p_front / attribute / yic / 1 0 0 / gt / YMAX
pset / p_front / zone / FOUT / ascii / ZONE

define / ZONE / 6
define / FOUT / {zone_prefix}_back
pset / p_back / attribute / yic / 1 0 0 / lt / YMIN
pset / p_back / zone / FOUT / ascii / ZONE

# ---------------------------------------------------
# Dump inspection files
# ---------------------------------------------------
dump / avs2 / HEX_OUT / MOHEX
dump / avs2 / TET_OUT / MOTET
dump / avs2 / DFN_OUT / MODFN

cmo / select / MODFN
# Dump out Material ID Dat file
cmo / modatt / MODFN / isn / ioflag / l
cmo / modatt / MODFN / x_four / ioflag / l
cmo / modatt / MODFN / fac_n / ioflag / l
cmo / modatt / MODFN / dfield / ioflag / l
cmo / modatt / MODFN / rf_field / ioflag / l
cmo / modatt / MODFN / a_b / ioflag / l
cmo / modatt / MODFN / b_a / ioflag / l
cmo / modatt / MODFN / xnorm / ioflag / l
cmo / modatt / MODFN / ynorm / ioflag / l
cmo / modatt / MODFN / znorm / ioflag / l
cmo / modatt / MODFN / evol_one / ioflag / l
cmo / modatt / MODFN / evol_all / ioflag / l
cmo / modatt / MODFN / numbnd / ioflag / l
cmo / modatt / MODFN / id_numb / ioflag / l
cmo / modatt / MODFN / evol_all / ioflag / l
cmo / modatt / MODFN / itp / ioflag / l
cmo / modatt / MODFN / icr / ioflag / l
cmo / modatt / MODFN / meshid / ioflag / l
cmo / modatt / MODFN / id_n_1 / ioflag / l
cmo / modatt / MODFN / id_n_2 / ioflag / l
cmo / modatt / MODFN / pt_gtg / ioflag / l
cmo / modatt / MODFN / imt1 / ioflag / l
dump / avs2 / matrix_cells.dat / MODFN / 0 0 2 0 


# ---------------------------------------------------
# Dump PFLOTRAN unstructured grid from tet mesh
# ---------------------------------------------------
cmo / select / MOTET
cmo / modatt / MOTET / itp / ioflag / l
cmo / modatt / MOTET / isn / ioflag / l
cmo / modatt / MOTET / icr / ioflag / l

dump / pflotran / PFLOTRAN_PREFIX / MOTET / nofilter_zero

finish
"""

    with open(script_name, "w") as f:
        f.write(script)

    return script_name


lx = 1
ly = 1 
lz = 1 

nx = 3
ny = 3
nz = 3 
epsilon = 1e-4 

write_lagrit_script(
        nx=nx,
        ny=ny,
        nz=nz,
        lx=lx,
        ly=ly,
        lz=lz,
        epsilon=epsilon,
    )

