dfnTrans: /Users/nataliia/Desktop/dfnGen-docs/Docs_PT/ParticleTracking_source/TrackingPart.c File Reference
TrackingPart.c File Reference
#include <stdio.h>
#include <search.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "FuncDef.h"
#include <unistd.h>
#include <time.h>
#include <sys/stat.h>
Data Structures
struct inpfile
struct lagrangian
struct intcoef
struct posit3d
struct tempout
Functions
void ParticleTrack ()
void CheckNewCell ()
struct intcoef CalculateWeights (int nn1, int nn2, int nn3)
void SearchNeighborCells (int nn1, int nn2, int nn3)
int InsideCell (unsigned int numc)
void PredictorStep ()
void CorrectorStep ()
void NeighborCells (int k)
void DefineTimeStep ()
int CheckDistance ()
double InOutFlowCell (int indcell, int int1, double nposx, double nposy)
void AcrossIntersection (int prevcell, int int1, int int2, int mixing_rule)
int StreamlineRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk, int neighborcellind[4], int neighborfracind[4], int prevfrac, int prevcell)
int CompleteMixingRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk)
void Moving2Center (int nnp, int cellnumber)
int Moving2NextCell (int stuck, int k)
double CalculateCurrentDT ()
int Xindex (int nodenum, int nnp)
int Yindex (int nodenum, int nnp)
void Moving2NextCellBound (int prevcell)
void ParticleOutput (int currentt, int fract_p)
void FinalPosition ()
struct lagrangian CalculateLagrangian (double xcurrent, double ycurrent, double zcurrent, double xprev, double yprev, double zprev)
double TimeDomainRW (double time_advect)
Variables
struct lagrangian lagvariable
unsigned int FLAG_OUT =0
unsigned int all_out =0
unsigned int np
unsigned int t
unsigned int nodeID =0
unsigned int avs_o =0
unsigned int traj_o =0
unsigned int curv_o =0
unsigned int no_out =0
unsigned int tdrw =0
unsigned int mixing_rule =1
unsigned int marfa =0
unsigned int plumec =0
unsigned int disp_o =0
unsigned int timecounter =0
unsigned int frac_o =0
unsigned int tfile =0
unsigned int tdrw_o =0
double tdrw_porosity =0.0
double tdrw_diffcoeff =0.0
double t_adv0 =0.0
double t_adv =0.0
double timediff =0.0
struct tempout * tempdata
Function Documentation
AcrossIntersection()
void AcrossIntersection (int prevcell, int int1, int int2, int mixing_rule)
Particle is moving through intersection line
Definition at line 2013 of file TrackingPart.c.
References CalculateWeights(), cell, vertex::cells, ChangeFracture(), CompleteMixingRandomSampling(), vertex::coord_xy, vertex::fracture, element::fracture, contam::intcell, mixing_rule, node, element::node_ind, np, particle, contam::position, contam::prev_pos, StreamlineRandomSampling(), element::veloc_ind, vertex::velocity, intcoef::weights, XindexC(), and YindexC().
CalculateCurrentDT()
double CalculateCurrentDT ()
Functions returns particle instanteneous time step
Definition at line 2527 of file TrackingPart.c.
References contam::cell, cell, node, element::node_ind, np, particle, vertex::timestep, element::veloc_ind, and contam::weight.
Referenced by CheckDistance(), CheckNewCell(), CorrectorStep(), and PredictorStep().
CalculateLagrangian()
struct lagrangian CalculateLagrangian (double xcurrent, double ycurrent, double zcurrent, double xprev, double yprev, double zprev)
Function calculates Lagrangian variables: tau and beta.
Definition at line 3140 of file TrackingPart.c.
References vertex::aperture, lagrangian::betta, CalculateVelocity3D(), contam::cell, cell, posit3d::cord3, lagrangian::initx, lagrangian::inity, lagrangian::initz, lagvariable, node, element::node_ind, np, particle, and lagrangian::tau.
CalculateWeights()
struct intcoef CalculateWeights (int nn1, int nn2, int nn3)
Function calculates interpolation weights for velocity instanteneous particles velocity and time step.
Definition at line 1416 of file TrackingPart.c.
References vertex::coord_xy, node, np, particle, intcoef::weights, Xindex(), and Yindex().
Referenced by AcrossIntersection(), CheckNewCell(), InOutFlowCell(), and InsideCell().
CheckDistance()
int CheckDistance ()
Function checks the distance from particle to intersection line when particles is located at the intersection triangular cell
Definition at line 1655 of file TrackingPart.c.
References CalculateCurrentDT(), contam::cell, cell, CheckNewCell(), vertex::coord_xy, vertex::fracture, fracture, vertex::indnodes, no_out, node, element::node_ind, np, vertex::numneighb, particle, ParticleOutput(), contam::position, PredictorStep(), contam::prev_pos, t, t_adv, t_adv0, contam::t_adv_diff, contam::t_diff, tdrw, tdrw_o, contam::time, timediff, TimeDomainRW(), Xindex(), and Yindex().
CheckNewCell()
void CheckNewCell ()
Function performs a check, did particle move to a new triangular cell during last time step or stayed at the same cell
Definition at line 1273 of file TrackingPart.c.
References CalculateCurrentDT(), CalculateWeights(), contam::cell, cell, FLAG_OUT, contam::fracture, node, element::node_ind, np, vertex::numneighb, particle, contam::position, contam::prev_pos, SearchNeighborCells(), contam::velocity, contam::weight, and intcoef::weights.
Referenced by CheckDistance().
CompleteMixingRandomSampling()
int CompleteMixingRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk)
Particle motion at a fracture intersection is determined by the streamline routing rule Arg 1: Cross product to define outgoing and incoming cells. Vector contains value for each cell at the intersection Arg 2: Vector of the speed squared for each cell at the intersection Arg 3: index of current cell in int1 node list Arg 4: int1 is the index of the node of the incoming cell that lies on the intersection Arg 5: indk gives the position in the list of the 4 intersection cells that is previous cell Return: The Exit cell at the intersection
Definition at line 2344 of file TrackingPart.c.
References vertex::cells, and node.
Referenced by AcrossIntersection().
CorrectorStep()
void CorrectorStep ()
Corrector step in Predictor-Corrector technique. Function calculates new particle position using calculated velocity in Predictor step.
Definition at line 1576 of file TrackingPart.c.
References CalculateCurrentDT(), contam::cell, cell, element::node_ind, np, particle, contam::position, contam::prev_pos, element::veloc_ind, and contam::velocity.
DefineTimeStep()
void DefineTimeStep ()
Function performs a loop through all the nodes in the mesh and defines a time step at each node. The time step of particles will be interpolated from time steps defined at each node.
Definition at line 1622 of file TrackingPart.c.
References nnodes, node, vertex::timestep, and vertex::velocity.
Referenced by main().
FinalPosition()
void FinalPosition ()
Function calculates particles final position at out-flow boundary
Definition at line 2996 of file TrackingPart.c.
References contam::cell, cell, vertex::cells, vertex::coord_xy, vertex::indnodes, node, element::node_ind, np, vertex::numneighb, particle, contam::position, contam::prev_pos, contam::time, Xindex(), and Yindex().
InOutFlowCell()
double InOutFlowCell (int indcell, int int1, double nposx, double nposy)
Function defines if velocities on cell vertices pointing in or out of intersection line
Definition at line 1949 of file TrackingPart.c.
References CalculateWeights(), contam::cell, cell, ChangeFracture(), vertex::coord_xy, contam::fracture, node, element::node_ind, np, particle, contam::position, element::veloc_ind, vertex::velocity, intcoef::weights, XindexC(), and YindexC().
InsideCell()
int InsideCell (unsigned int numc)
Function checks if particle is in the cell (numc is cell ID)
Definition at line 1487 of file TrackingPart.c.
References CalculateWeights(), contam::cell, cell, contam::intcell, node, element::node_ind, np, particle, contam::weight, and intcoef::weights.
Referenced by InitCell(), InitPos(), Moving2Center(), and NeighborCells().
Moving2Center()
void Moving2Center (int nnp, int cellnumber)
Function moves particle to the center of the same cell
Definition at line 2440 of file TrackingPart.c.
References cell, vertex::coord_xy, InsideCell(), node, element::node_ind, particle, contam::position, Xindex(), and Yindex().
Referenced by InitPos(), Moving2NextCell(), and Moving2NextCellBound().
Moving2NextCell()
int Moving2NextCell (int stuck, int k)
Functions performs the movement of particle from one cell to the center of neighbouring cell.
Definition at line 2471 of file TrackingPart.c.
References contam::cell, cell, vertex::cells, fracture, Moving2Center(), node, np, and particle.
Moving2NextCellBound()
void Moving2NextCellBound (int prevcell)
In the pathological rare case, when particle is out of fracture, the function is called and it's moving particle to internal cell
Definition at line 2572 of file TrackingPart.c.
References contam::cell, cell, vertex::cells, fracture, Moving2Center(), node, element::node_ind, np, and particle.
NeighborCells()
void NeighborCells (int k)
Function checks neighboring cells to find a particle
Definition at line 1600 of file TrackingPart.c.
References vertex::cells, fracture, InsideCell(), node, np, and particle.
Referenced by SearchNeighborCells().
ParticleOutput()
void ParticleOutput (int currentt, int fract_p)
The function of particles trajectories outputs. Function is called at every intersection and outputs to file at each segment of particles trajectory: from intersection to intersection. The curvature of the trajectory is defined and dictate number of time steps for outputs (unless user requested every time step output).
Definition at line 2669 of file TrackingPart.c.
References tfile.
Referenced by CheckDistance().
ParticleTrack()
void ParticleTrack ()
The main driving function of particles tracking procedure.
The all necessary options for particle tracking and for the outputs are read from input control file.
The subroutine for particle initial positions is called.
External loop on paticles is organised. One particle at a time.
Internal loop on time steps, where particles are mobing through fracture network. 4.1 Predictor -corrector technique is used for particles to move through fractures. 4.2 Complete mixing or streamline routing rule (defined by user) are used on intersections. 4.3 Particles data outputs.
Definition at line 66 of file TrackingPart.c.
References all_out, avs_o, Control_File(), Control_File_Optional(), Control_Param(), vertex::coord, curv_o, disp_o, inpfile::filename, inpfile::flag, flag_w, FlowInWeight(), frac_o, vertex::fracture, InitPos(), maindir, marfa, mixing_rule, no_out, node, nodezonein, nodezoneout, np, OpenFile(), inpfile::param, plumec, String_Compare(), t, tdrw, tdrw_diffcoeff, tdrw_o, tdrw_porosity, tfile, timesteps, timeunit, and traj_o.
Referenced by main().
PredictorStep()
void PredictorStep ()
Predictor step in Predictor-Corrector technique. Function calculates new velocities and new particle position.
Definition at line 1541 of file TrackingPart.c.
References CalculateCurrentDT(), contam::cell, cell, node, element::node_ind, np, particle, contam::position, vertex::pressure, contam::pressure, contam::prev_pos, element::veloc_ind, vertex::velocity, contam::velocity, and contam::weight.
Referenced by CheckDistance().
SearchNeighborCells()
void SearchNeighborCells (int nn1, int nn2, int nn3)
Function performs a search of neighbouring cells of current particles position.
Definition at line 1450 of file TrackingPart.c.
References cell, NeighborCells(), np, and particle.
Referenced by CheckNewCell().
StreamlineRandomSampling()
int StreamlineRandomSampling (double products[4], double speedsq[4], int indj, int int1, int indk, int neighborcellind[4], int neighborfracind[4], int prevfrac, int prevcell)
Particle motion at a fracture intersection is determined by the streamline routing rule Arg 1: Cross product to define outgoing and incoming cells. Vector contains value for each cell at the intersection Arg 2: Vector of the speed squared for each cell at the intersection Arg 3: index of current cell in int1 node list Arg 4: int1 is the index of the node of the incoming cell that lies on the intersection Arg 5: indk gives the position in the list of the 4 intersection cells that is previous cell Arg 6: Vector of the indicies for the 4 neighboring cells Arg 7: Vector of the fracture index for the 4 neighboring cells Arg 8: Fracture a particle is coming from Arg 9: Cell index a particle is coming from Return: The Exit cell at the intersection
Definition at line 2142 of file TrackingPart.c.
References cell, vertex::cells, fracture, and node.
Referenced by AcrossIntersection().
TimeDomainRW()
double TimeDomainRW (double time_advect)
Time Domain Random Walk (TDRW) procedure. Returns a diffusion time of particle per racture. Called at each intersection.
Definition at line 3175 of file TrackingPart.c.
References vertex::aperture, contam::cell, cell, material::firstnode, contam::fracture, fracture, node, element::node_ind, np, particle, pi, tdrw_diffcoeff, tdrw_porosity, and timediff.
Referenced by CheckDistance().
Xindex()
int Xindex (int nodenum, int nnp)
Functions returns the index of X coordination of intersection node
Definition at line 2550 of file TrackingPart.c.
References fracture, node, and particle.
Referenced by CalculateWeights(), CheckDistance(), FinalPosition(), and Moving2Center().
Yindex()
int Yindex (int nodenum, int nnp)
Functions returns the index of Y coordination of intersection node
Definition at line 2561 of file TrackingPart.c.
References fracture, node, and particle.
Referenced by CalculateWeights(), CheckDistance(), FinalPosition(), and Moving2Center().
Variable Documentation
all_out
unsigned int all_out =0
Definition at line 29 of file TrackingPart.c.
Referenced by ParticleTrack().
avs_o
unsigned int avs_o =0
Definition at line 30 of file TrackingPart.c.
Referenced by ParticleTrack().
curv_o
unsigned int curv_o =0
Definition at line 30 of file TrackingPart.c.
Referenced by ParticleTrack().
disp_o
unsigned int disp_o =0
Definition at line 31 of file TrackingPart.c.
Referenced by ParticleTrack().
FLAG_OUT
unsigned int FLAG_OUT =0
Definition at line 29 of file TrackingPart.c.
Referenced by CheckNewCell().
frac_o
unsigned int frac_o =0
Definition at line 31 of file TrackingPart.c.
Referenced by ParticleTrack().
lagvariable
struct lagrangian lagvariable
Definition at line 28 of file TrackingPart.c.
Referenced by CalculateLagrangian().
marfa
unsigned int marfa =0
Definition at line 31 of file TrackingPart.c.
Referenced by OutputMarPlumDisp(), and ParticleTrack().
mixing_rule
unsigned int mixing_rule =1
Definition at line 30 of file TrackingPart.c.
Referenced by AcrossIntersection(), and ParticleTrack().
no_out
unsigned int no_out =0
Definition at line 30 of file TrackingPart.c.
Referenced by CheckDistance(), and ParticleTrack().
nodeID
unsigned int nodeID =0
Definition at line 30 of file TrackingPart.c.
np
unsigned int np
index of current particle, idex in particle's loop
Definition at line 30 of file TrackingPart.c.
Referenced by AcrossIntersection(), CalculateCurrentDT(), CalculateLagrangian(), CalculatePosition3D(), CalculateVelocity3D(), CalculateWeights(), ChangeFracture(), CheckDistance(), CheckNewCell(), CorrectorStep(), FinalPosition(), FlowInWeight(), InitParticles_flux(), InOutFlowCell(), InsideCell(), Moving2NextCell(), Moving2NextCellBound(), NeighborCells(), ParticleTrack(), PredictorStep(), SearchNeighborCells(), and TimeDomainRW().
plumec
unsigned int plumec =0
Definition at line 31 of file TrackingPart.c.
Referenced by OutputMarPlumDisp(), and ParticleTrack().
t
unsigned int t
Definition at line 30 of file TrackingPart.c.
Referenced by CheckDistance(), and ParticleTrack().
t_adv
double t_adv =0.0
Definition at line 32 of file TrackingPart.c.
Referenced by CheckDistance().
t_adv0
double t_adv0 =0.0
Definition at line 32 of file TrackingPart.c.
Referenced by CheckDistance().
tdrw
unsigned int tdrw =0
Definition at line 30 of file TrackingPart.c.
Referenced by CheckDistance(), and ParticleTrack().
tdrw_diffcoeff
double tdrw_diffcoeff =0.0
Definition at line 32 of file TrackingPart.c.
Referenced by ParticleTrack(), and TimeDomainRW().
tdrw_o
unsigned int tdrw_o =0
Definition at line 31 of file TrackingPart.c.
Referenced by CheckDistance(), and ParticleTrack().
tdrw_porosity
double tdrw_porosity =0.0
Definition at line 32 of file TrackingPart.c.
Referenced by ParticleTrack(), and TimeDomainRW().
tempdata
struct tempout* tempdata
Definition at line 56 of file TrackingPart.c.
tfile
unsigned int tfile =0
Definition at line 31 of file TrackingPart.c.
Referenced by ParticleOutput(), and ParticleTrack().
timecounter
unsigned int timecounter =0
Definition at line 31 of file TrackingPart.c.
timediff
double timediff =0.0
Definition at line 32 of file TrackingPart.c.
Referenced by CheckDistance(), and TimeDomainRW().
traj_o
unsigned int traj_o =0
Definition at line 30 of file TrackingPart.c.
Referenced by OutputMarPlumDisp(), and ParticleTrack().